### ISSUE TITLE
Improve handling of how votes are presented in the Amendment API

### ISSUE THREAD

**Issue by rgup** [LibraryOfCongress/api.congress.gov#1]
Actions from the amendments endpoint are missing vote links (except when the latest action has a vote).  Votes on amendment do not match the expected output in the BILLSTATUS documentation.
 
Here’s an example from the [user’s github issue](https://github.com/usgpo/bill-status/issues/177): BILLSTATUS-114hr5278
 
For our govinfo bulkdata, line 1195 has Amendment 8, but there’s no link to the associated roll call vote..
 
To help illustrate, here’s what I believe we are expecting from the following url (colon removed to keep it from being garbled by ATP safelinks)
https //api.data.gov/congress/v2/amendment/114/hamdt/1163/actions?format=xml&api_key={{key}}
 
 
<api-root>
                <actions>
                                <item>
                                                <actionDate>2016-06-09</actionDate>
                                                <actionTime>18:11:58</actionTime>
                                                <links/>
                                                <text>On agreeing to the Torres amendment (A008) Failed by recorded vote: 196 - 225 (Roll no. 287).</text>
                                                <type>Floor</type>
                                                <actionCode>H32111</actionCode>
                                                <sourceSystem>
                                                                <code>2</code>
                                                                <name>House floor actions</name>
                                                </sourceSystem>
                                                There should be a section like this here:
<links>
<link>
    <name>Roll no. 287</name>
    <url>https://clerk.house.gov/evs/2016/roll287.xml</url>
</link>
</links>
                                                <committee/>
                                </item>
                                <item>
                                                <actionDate>2016-06-09</actionDate>
                                                <actionTime>17:40:01</actionTime>
                                                <links/>
                                                <text>Amendment (A008) offered by Mrs. Torres. (consideration: CR H3632-3634; text: CR H3633)</text>
                                                <type>Floor</type>
                                                <actionCode>H3A100</actionCode>
                                                <sourceSystem>
                                                                <code>2</code>
                                                                <name>House floor actions</name>
                                                </sourceSystem>
                                                <committee/>
                                </item>

**Comment by aweiss27** [comment]
Vote URLs are present at the actions sub-level of the amendment API (e.g., https://api.congress.gov/v3/amendment/114/hamdt/1163/actions?api_key=).
