### ISSUE TITLE
PowerBI Power Query Authentication  - R method

### ISSUE THREAD

**Issue by wjb3law** [LibraryOfCongress/api.congress.gov#106]
I'm using R to write a PowerBI query to make a simple API request but am receiving "Access is forbidden" with the my credentials. Has anyone tried using this method?

**Comment by mnewatloc** [comment]
We haven't used R as an API client, but it should work the same way as API clients in other languages. We have tested with clients written in Python and Java. Would you be willing to share screenshots of the issues you're having?

**Comment by wjb3law** [comment]
Thanks! Here is the query for powerBI and a screenshot of the access error: 
let
    /**************************************************************************
    BEGINNING OF USER CONFIGURABLE OPTIONS
    
    Review and update the configuration items below with the appropriate values
    for the target Congress.gov (CGOV) API environment and client credentials
    */



       
    /**************************************************************************
    cgov_api_endpoint_url is the fully-qualified URL for the CGOV API endpoint 
	you want to retrieve data from
    
        Example value: https://api.congress.gov/v3/bill
        
    */    
    
    cgov_api_endpoint_url = "https://api.congress.gov/v3/bill",

       
        
    /**************************************************************************
    personal_access_token is the token generated through the Personal Access 
    Tokens page in CGOV
    
        Example value: 24B1497BFD20399ADAB1B8F6D06B204FF
		(note this example is a made-up token and is not valid in any specific CGOV 		
		instance)
    */
    
    cgov_api_key = "[insert api key]",

    
    /**************************************************************************
    request_timeout_in_minutes is used to determine how long the web request
    to the CGOV API will wait for data to return before timing out. If requests
    using this script time out waiting for a response from the API, consider 
    increasing this value and trying again.    
    */
    
    request_timeout_in_minutes = 10,

    

    /**************************************************************************
    END OF USER CONFIGURABLE OPTIONS - DO NOT EDIT ANY CONTENT BELOW THIS LINE
    
    The remaining portion of this script will use the values provided above
    to retrieve data from the CGOV API endpoint URL.
    */

    data = Table.FromRecords(
        Json.Document(
            Web.Contents(
                cgov_api_endpoint_url,
                    [
                        Headers = 
                        [
                            #"Authorization"="Bearer "&cgov_api_key,
                            #"Content-Type"="application/json"
                        ],
                        Timeout = #duration(0,0,request_timeout_in_minutes,0)
                    ]
                )
            )
        )
in
    data

![image](https://github.com/LibraryOfCongress/api.congress.gov/assets/120422975/8453aaec-5dc0-4be4-a7c3-2a3b240bd37c)

**Comment by wjb3law** [comment]
Thank you! I reset my header as suggested and this resolved the access forbidden message. I am now receiving "We cannot convert a value of type Record to type List. Details:
Value=[Record]
Type=[Type]"

**Comment by jonquandt** [comment]
@wjb3law - since your API access issue is resolved, I think your next step would be to do some additional digging into Power Query documentation or communities tailored to that tool. 

From my experience with PowerQuery, you may need to back up a few steps and start with the most basic request. It seems like you're trying to combine steps converting the json response directly into a table instead of getting the json back and then implementing a step to convert to a table (which is admittedly, usually an automatic transform step that happens when you create an initial query like this).

**Comment by wjb3law** [comment]
Thanks! I appreciate the help. I was able to get it to work and have data pulled successfully. I copied an automatic transform function from json to list and then added those parameters to the header arguments for a web query.

**Comment by apreiter18** [comment]
If it is alright with you, @wjb3law, I am going to close this issue. Please let me know if you have any questions - thanks!
