### ISSUE TITLE
Retrieve congressional records

### ISSUE THREAD

**Issue by wtsong** [LibraryOfCongress/api.congress.gov#108]
I was wondering if there is a way to retrieve daily congressional records once `CongressionalRecordEndpoint` returns the corresponding URL.

For example, the congressional record endpoint returns the URL 
`[{'Part': '1', 'Url': 'https://www.congress.gov/117/crec/2022/12/30/168/203/CREC-2022-12-30-dailydigest.pdf'}]`
for a particular section. How do I then download the corresponding PDF, or alternatively retrieve the corresponding html pages, such as each section in "https://www.congress.gov/congressional-record/volume-168/issue-203/house-section"?

Thanks very much.

**Comment by mnewatloc** [comment]
Sorry to be so late in responding. You should be able to do this now. Let us know if you're still having issues.
