### ISSUE TITLE
curl section in openapi UI shows xml even if the example request asks for json

### ISSUE THREAD

**Issue by joshrotenberg** [LibraryOfCongress/api.congress.gov#110]
<img width="924" alt="Screenshot 2023-07-10 at 8 44 28 AM" src="https://github.com/LibraryOfCongress/api.congress.gov/assets/3231/1837866f-5edf-4127-b2a4-a0158a25d3c9">

**Comment by mnewatloc** [comment]
Thanks for the screenshot. I believe you need to specify JSON in the Responses dropdown.
