### ISSUE TITLE
Executive Communications - "list index out of range (IndexError)" error message

### ISSUE THREAD

**Issue by jonquandt** [LibraryOfCongress/api.congress.gov#121]
We are pulling a list of Executive communications using the following:

https://api.congress.gov/v3/house-communication/117/ec?api_key=DEMO_KEY

For some of the results returned, when we follow the `url` value, we get a "list index out of range (IndexError)" error message. Here is an example:

https://api.congress.gov/v3/house-communication/117/ec?offset=2750&limit=250&format=json&api_key=DEMO_KEY

returns EC 2634:
```JSON 
 {
      "chamber": "House",
      "communicationType": {
        "code": "EC",
        "name": "Executive Communication"
      },
      "congress": 117,
      "number": 2634,
      "updateDate": "2021-11-13",
      "url": "https://api.congress.gov/v3/house-communication/117/ec/2634?format=json"
    },
```

but following the url for that item:
https://api.congress.gov/v3/house-communication/117/ec/2634?format=json&api_key=DEMO_KEY

returns the following:
```JSON
{
    "error": "list index out of range (IndexError)",
    "request": {
        "communicationNum": "2634",
        "congress": "117",
        "contentType": "application/json",
        "execCommunicationType": "ec",
        "format": "json"
    }
}
```

Here is another example:

https://api.congress.gov/v3/house-communication/117/ec/2647?format=xml

This applies to both xml and json format.

The error appears to be only affecting certain results, but is consistent in the results that it is affecting.

**Comment by jonquandt** [comment]
Additional example:
https://api.congress.gov/v3/house-communication/117/ec/3063?format=json

**Comment by mnewatloc** [comment]
Thank you for bringing this to our attention. We have created a ticket for this issue.

**Comment by ryparker** [comment]
Came across another with this issue:
- api.congress.gov/v3/house-communication/118/ec/653?format=json
