### ISSUE TITLE
feat: request for a community discord channel

### ISSUE THREAD

**Issue by ryparker** [LibraryOfCongress/api.congress.gov#124]
Would there be any interest in forming a discord channel? This could be a place for developers using APIs such as congress.gov to discuss interesting implementations, ask questions, or share resources.

Is this something the LoC or Congressional data task force would be able to create?

Could we also make it a place for USGPO devs?

**Comment by c4lliope** [comment]
I had some good success deploying Zulip on-premises in my company. There is surely much more of a chance the LoC is able to use the open-source, on-premise Zulip app than anything on Discord.

I am happy to deploy a second copy of Zulip for the Congressional Data Task Force (I could use my spare https://encoder.buzz domain), though I'm nearly sure the Congressional employees are going to be barred from any of these chat programs unless they're:

* On-premise open source deployments
* A screened contractor like GitHub (run by Microsoft)

The single security issue I came across in Zulip is that mobile notifications need to go through a couple third-party companies before they reach users' phones. I imagine LoC needs to keep an eye on these messages, so any congressional deployment of Zulip should use the `PUSH_NOTIFICATION_REDACT_CONTENT` flag for now: github.com/zulip/zulip/pull/6936

Some engineers are making progress this year on end-to-end encryption on Zulip's notifications, so any on-premise deployments should soon be as secure, and as usable, as possible.
https://github.com/zulip/zulip/issues/6954
https://github.com/zulip/zulip/pull/26262

Zulip is an ideal choice for gov organizations, and I highly encourage adoption. The deployment used by my company (and numerous engineers here in DC) is https://labori.us

**Comment by mnewatloc** [comment]
We've discussed this but feel we don't have time or resources to maintain or moderate a channel.

**Comment by ryparker** [comment]
I created a discord called Congress Devs: https://discord.gg/PPMwDHuQxu

Anyone working with Congress data is welcome to join
