### ISSUE TITLE
Include the API definition file

### ISSUE THREAD

**Issue by Gmanicus** [LibraryOfCongress/api.congress.gov#128]
Hi there,

Thank you all for the hard work. The API looks like an incredible resource, and I'm excited to start using it.

I have a suggestion. I was looking at generating a local Typescript API service for the congress.gov API from the swagger documentation. It looks like you could do this with a service like NSwag, but that relies on a swagger/openApi definition file. Is there a chance that you could add the swagger definition file to the repository or expose it via URL? ([Looking this up](https://stackoverflow.com/questions/48525546/how-to-export-swagger-json-or-yaml), it appears to be most commonly found under `/v#/api-docs.yaml` or `/v#/swagger.json`)

EDIT: I was able to retrieve the specification JSON by going to the developer console, running `ui.getConfigs()` and copying the `spec` object. Putting this through NSwag appears to have generated a working API service. 

Thanks

**Comment by mnewatloc** [comment]
Thanks for the input. We've created a ticket to add the swagger definition file to the repository.

**Comment by Gmanicus** [comment]
Happened to notice that [this appears to be a duplicate of an older issue](https://github.com/LibraryOfCongress/api.congress.gov/issues/29).

**Comment by apreiter18** [comment]
@Gmanicus - Hi Grant, we added our swagger file [here](https://github.com/LibraryOfCongress/api.congress.gov/blob/main/api_client/swagger.yaml). Let me know if you have any questions! Thanks!
