### ISSUE TITLE
/bills from January 1st returns 147k pagination count

### ISSUE THREAD

**Issue by Gmanicus** [LibraryOfCongress/api.congress.gov#131]
Hi there,

I am attempting to retrieve all bills starting from January 1st via the `/bills` endpoint with a `fromDateTime` of `2023-01-01T00:00:00Z` with a limit of `250` for each request.

![image](https://github.com/LibraryOfCongress/api.congress.gov/assets/11013079/3dbecab9-5aaf-4a83-819d-b955ddadb156)

591 pages at 250 bills per page = ~147k bills. On Congress.gov, I see ~10k bills since January 1st.

This seems to return many results from many congresses as far back as `103` with the latest action being in 1993.

It seems to start _only_ returning results from congress 118 starting from July 1st.

Are these updated dates correct? Potentially related to #111 and #112 

The URL: `https://api.congress.gov/v3/bill?fromDateTime=2023-01-01T00:00:00Z`

**Comment by mnewatloc** [comment]
It looks like you're searching by update date. The Government Publishing Office recently reissued most bills and we reprocessed them, so that count is actually correct.

**Comment by Gmanicus** [comment]
Ah, I see. Thank you for the explanation!
