### ISSUE TITLE
Error when using /bills `sort=updateDate+asc` starting from July 1st

### ISSUE THREAD

**Issue by Gmanicus** [LibraryOfCongress/api.congress.gov#132]
An error is thrown when attempting to retrieve bills since July 1st while sorting by oldest first.

```
Reverse for 'bill_details' with keyword arguments '{'congress': 6, 'billType': 'cen_doc_h', 'billNumber': '73'}' not found. 2 pattern(s) tried: ['v3/bill/(?P<congress>(\\\\d+))/(?P<billType>(hr|hres|hconres|hjres|s|sres|sconres|sjres))/(?P<billNumber>(\\\\d+\\\\xbd?M{0,4}(CM|CD|D?C{0,3})(XC|XL|L?X{0,3})(IX|IV|V?I{0,3})|M{0,4}(CM|C?D|D?C{1,3})(XC|XL|L?X{0,3})(IX|IV|V?I{0,3})|M{0,4}(CM|CD|D?C{0,3})(XC|X?L|L?X{1,3})(IX|IV|V?I{0,3})|M{0,4}(CM|CD|D?C{0,3})(XC|XL|L?X{0,3})(IX|I?V|V?I{1,3})?))(?P<file_ext>(\\\\.xml|\\\\.json|/))?$(?i)', 'v2/bill/(?P<congress>(\\\\d+))/(?P<billType>(hr|hres|hconres|hjres|s|sres|sconres|sjres))/(?P<billNumber>(\\\\d+))(?P<file_ext>(\\\\.xml|\\\\.json|/))?$(?i)'] (NoReverseMatch)
```

URL: `https://api.congress.gov/v3/bill?sort=updateDate+asc&fromDateTime=2023-07-01T00:00:00Z`

**Comment by mnewatloc** [comment]
Thank you for bringing this to our attention. This appears to be impacting only 7/1/2023 through 7/6/2023. We've opened a ticket.

**Comment by rbram** [comment]
Hello. This issue has been resolved. Search results should appear for July 1, 2023 now. The error message is no longer displaying.

**Comment by Gmanicus** [comment]
@rbram Thanks. Is that specific instance of this issue resolved, or has this issue been patched for other/future time periods as well? I ask because I will close the issue if it's no longer needed.

**Comment by rbram** [comment]
Hello. The bug has been investigated and patched. We do not anticipate that this will occur again after work was completed. If you have any questions, or notice a similar bug, please reach out and we will work to address it in the future.

**Comment by Gmanicus** [comment]
Great, thanks!
