### ISSUE TITLE
RSS Feed Behind Cloudflare

### ISSUE THREAD

**Issue by JonathanWilbur** [LibraryOfCongress/api.congress.gov#138]
Hello, I don't know if this is the right place to report this or not, but the RSS feeds under https://www.congress.gov/rss/ (such as https://www.congress.gov/rss/most-viewed-bills.xml) are behind Cloudflare, and Cloudflare blocks non-human requests at this URL. I cannot get any RSS reader to work with this endpoint because Cloudflare blocks it with an HTTP 403 error, though I can open it in my web browser just fine. This defeats the point of having an RSS feed, since it is meant to be machine-readable.

Thank you!

**Comment by rbram** [comment]
Thanks for your feedback. We have made this change. Please let us know if you have any other issues.

**Comment by JonathanWilbur** [comment]
It works now! Thank you for fixing this so quickly!
