### ISSUE TITLE
Congress.gov Public Forum API Presentations

### ISSUE THREAD

**Issue by rbram** [LibraryOfCongress/api.congress.gov#140]
Hello. On 9/13, at 1pm, the Library is going to hold a Congress.gov Public Forum. You can participate online or in-person. This Forum will provide an update on the latest Congress.gov enhancements and it will also be a listening session where the Library and our data partners can learn how we can better serve your legislative information needs. 
One of the items we will discuss is the Congress.gov API. As part of that discussion, we are interested in having users discuss their unique applications that have incorporated data from the Congress.gov API. If you would be interested in providing a two-minute presentation, would you please let us know by responding to this issue? 
You can learn more about the Forum here: https://blogs.loc.gov/law/2023/08/join-us-for-a-congress-gov-public-forum-on-september-13th/

**Comment by Gmanicus** [comment]
Hi @apreiter18. I see that the next Public Forum is next month on the 18th.

I have been working on a web application that utilizes the Congress.gov API significantly over the past few years (coincidentally starting just months of the after the API was first launched). Unfortunately, it's not publicly accessible yet, but it's looking like I may be able to launch it within the next few weeks (I can provide documentation on it before then if desired).

With that said, is the LOC interested in a two minute presentation on how this web application incorporates the Congress.gov API as part of the forum?

**Comment by rbram** [comment]
Hello @Gmanicus Thanks. Could you please provide the documentation that you mentioned? Would you be presenting in-person or remotely?

**Comment by Gmanicus** [comment]
@rbram Hi Mr. Brammer,

I don't think I would be able to appear in-person, but I can present remotely if that is possible as part of the forum. I'll prepare the documentation and get that over to you by the end of today. Is there a contact email I should use, or would you like me to just attach it to this issue?

**Comment by apreiter18** [comment]
You can attach it to this issue if that works for you, @Gmanicus - thank you!

**Comment by Gmanicus** [comment]
Here's a very quick demo @rbram @apreiter18 

https://github.com/user-attachments/assets/e53fa28c-5427-4be9-8e77-8e7e3538d060

**Comment by rbram** [comment]
Thanks @Gmanicus Would you please pre-record a short presentation for the Forum? Would you please attach it by 9/13 so I can test the playback in advance of the Forum? Thank you!

**Comment by Gmanicus** [comment]
Will do!

**Comment by rbram** [comment]
Hello @Gmanicus In addition to the recording, would you please fill out this event release form and email it to me at rbram@loc.gov? Thank you!
[Release Form.docx](https://github.com/user-attachments/files/16980341/Release.Form.docx)

**Comment by Gmanicus** [comment]
@rbram Sure thing, and I should have that recording over to you before tomorrow.
