### ISSUE TITLE
Add direct video links to the Committee Meeting Details endpoint

### ISSUE THREAD

**Issue by showerst** [LibraryOfCongress/api.congress.gov#141]
Hi, currently the [committee meeting details endpoint](https://api.congress.gov/#/committee-meeting/committee_meeting_detail) provides links to the congress.gov page that embeds a youtube video of the event. This is great, but if you want the actual video you still have to go scrape the congress.gov page, which is behind cloudflare.

Would it be possible to provide the raw youtube url, either in that field or an additional one? 

Thanks!

**Comment by mnewatloc** [comment]
Thanks for your comment. This is something we're considering for the future.
