### ISSUE TITLE
`originChamberCode` is missing from Bill Details response

### ISSUE THREAD

**Issue by Gmanicus** [LibraryOfCongress/api.congress.gov#144]
For example: `https://api.congress.gov/v3/bill/118/hr/3746`

`originChamberCode` exists in the bulk Bill endpoints, but not the Bill Detail endpoints.

**Comment by mnewatloc** [comment]
Thanks for pointing that out. We'll create a ticket to add it.

**Comment by Gmanicus** [comment]
Looks like this is another duplicate. My apologies. #86
