### ISSUE TITLE
Pagination count appears to be incorrect when setting custom limit

### ISSUE THREAD

**Issue by Gmanicus** [LibraryOfCongress/api.congress.gov#145]
When requesting bills updated today in bulk with no limit set, the count is `640`...
![image](https://github.com/LibraryOfCongress/api.congress.gov/assets/11013079/cf80b3b6-7869-4830-a4dc-4fbd1a8e4296)

`https://api.congress.gov/v3/bill/?fromDateTime=2023-08-30T00:00:00Z`

However, after setting the page limit to `250`...
![image](https://github.com/LibraryOfCongress/api.congress.gov/assets/11013079/1786586b-c765-47ce-837e-f060dc28bf07)

...a pagination count of `640` is still received.

`https://api.congress.gov/v3/bill/?fromDateTime=2023-08-30T00:00:00Z&limit=250`

**Comment by mnewatloc** [comment]
I think that's how it's supposed to work. You're limiting results to 250, but the total results are still 640.

**Comment by Gmanicus** [comment]
Ah, my apologies. I misunderstood that as the total number of pages, not the count of items.
