### ISSUE TITLE
Bill sub endpoints no longer accept uppercase bill type

### ISSUE THREAD

**Issue by Gmanicus** [LibraryOfCongress/api.congress.gov#150]
The `/bill/{congress}/{billType}/{billNumber}/...` endpoints used to be case-insensitive for bill types such as `HR`, `HRES`, but now only accept them in lowercase.

They now return `404 Not Found`. E.g:
```
{
    "error": "Unknown resource: bill/118/HR/4755/actions"
}
```

The details endpoint is still case-insensitive.

**Comment by ryparker** [comment]
This is intentional, see this change log entry: https://github.com/LibraryOfCongress/api.congress.gov/blob/main/ChangeLog.md#change-3-2

**Comment by Gmanicus** [comment]
Ah, I see! Thanks for pointing that out @ryparker
