### ISSUE TITLE
(partitioned treaty API): lower case suffix not supported

### ISSUE THREAD

**Issue by ryparker** [LibraryOfCongress/api.congress.gov#153]
The partitioned treaty API does not return the expected result unless the suffix is capitalized. I was expecting all params to support lower case which would be inline with this change log entry: https://github.com/LibraryOfCongress/api.congress.gov/blob/main/ChangeLog.md#change-3-2

For example:
```sh
curl 'https://api.congress.gov/v3/treaty/114/13/a?format=json&api_key=<REPLACE_ME>'
```

Returns:
```json
{
    "error": "Unknown resource: treaty/114/13/a"
}
```

But capitalizing the suffix returns the expected result:
```sh
curl 'https://api.congress.gov/v3/treaty/114/13/A?format=json&api_key=<REPLACE_ME>'
```

**Comment by rbram** [comment]
Thank you for your feedback. We have created a ticket to address this.
