### ISSUE TITLE
Issue about daily congressional record endpoint

### ISSUE THREAD

**Issue by LatifaTam** [LibraryOfCongress/api.congress.gov#154]
For the **daily congressional record** endpoint, the formatted text won't match with the pdf file. 
Here is the URL I tried to access: https://api.congress.gov/v3/daily-congressional-record/167/21/articles?api_key=[my_key]
It successfully returns a JSON format response, but it seems that the .txt file doesn't include all the text from the .pdf file. 

Here are two examples: 
formatted text: https://www.congress.gov/117/crec/2021/02/04/modified/CREC-2021-02-04-pt2-PgD93-2.htm
pdf file: https://www.congress.gov/117/crec/2021/02/04/CREC-2021-02-04-pt2-PgD93-2.pdf
The same thing happened to other links I got from various calls on the daily congressional record endpoint.

**Comment by mnewatloc** [comment]
Unless I'm misunderstanding your note, that appears to be correct. Both urls are pointing to PgD93-2, which is the second article on page D92. Congressional record articles are designated by “Bodoni dashes,” that long horizontal bar near the bottom of the second column here:
https://www.congress.gov/117/crec/2021/02/04/CREC-2021-02-04-pt2-PgD93-2.pdf

It’s more obvious when there are many articles on one page, like this:
https://www.congress.gov/congressional-record/volume-169/issue-162/senate-section/page/S4901

You can see that each url there is different, even though they’re pointing to the same Congressional Record page.

**Comment by LatifaTam** [comment]
Hi thank you for responding. Sure, those url talk about the same thing. However, it seems that the PDF has more information than the formatted text. For example, the "ORGANIZATIONAL MEETING" and the paragraphs following are not included. Also, the PDF mentioned COVID-19 and some relevant details, but none of those are included in the formatted text. Does that make sense?

**Comment by mnewatloc** [comment]
There is no D93-1, since the first article on the page carries over from a previous page. 

You can link to the whole page: 
https://www.congress.gov/117/crec/2021/02/04/167/21/modified/CREC-2021-02-04-pt1-PgD93.htm
Or to the previous article:
https://www.congress.gov/117/crec/2021/02/04/167/21/modified/CREC-2021-02-04-pt1-PgD92-2.htm
