### ISSUE TITLE
How can I access the member container at the item level

### ISSUE THREAD

**Issue by mirandar9936** [LibraryOfCongress/api.congress.gov#157]
I am trying to access the member container at the item level but get a key error. 
Here is the code I am using: 

# Get members information
response = requests.get(url)
response_json = response.json()
print(response_json["members"][0]["member"])

Always get key error, can someone please help me.

**Comment by rbram** [comment]
Hello. Thanks for your question. Could you please provide the request URL and screenshots of what you are doing/seeing? Thanks.

**Comment by mirandar9936** [comment]
![Screenshot 2023-10-19 103218](https://github.com/LibraryOfCongress/api.congress.gov/assets/88207271/6bd0b110-8f4a-46cc-af1f-7b67ab2192ea)
![python code](https://github.com/LibraryOfCongress/api.congress.gov/assets/88207271/64fdd54c-271d-4b9e-93a3-1188d116095a)

I do not see the "member" container

**Comment by mnewatloc** [comment]
Thank you for bringing this to our attention. We’ve opened a bug ticket. It appears that the first item is always empty. Starting from 1 instead of 0 should work until the fix is in place.

**Comment by mirandar9936** [comment]
I tried accessing starting at 1 but I do not see the 'member' key. Nor do I see the individual url for the congress person's website? Am I using the wrong endpoint? 
![python code](https://github.com/LibraryOfCongress/api.congress.gov/assets/88207271/8ca8ac56-bc37-49
![api response](https://github.com/LibraryOfCongress/api.congress.gov/assets/88207271/66ad4ac5-f6d1-44b0-92b5-cd158e34dc6e)
d5-8ad2-1c299c21b857)

**Comment by Gmanicus** [comment]
Ah, I think you might be misunderstanding the documentation. All of the available endpoints along with example requests & responses can be seen here: https://api.congress.gov/#/member/member_list

The documentation says this:
![image](https://github.com/LibraryOfCongress/api.congress.gov/assets/11013079/03a1707b-4b9c-4a11-9fe2-abe7073b001d)

Each item in the `members` array is a `member`, but since it's not a JSON object, each item won't have a key of "member". Instead, each JSON object item in the `members` array _is_ a "member".

**Comment by mirandar9936** [comment]
Thank you for your response. This makes sense. My final question is, the endpoint https://api.congress.gov/v3/member?api_key=[INSERT_KEY], does not contain the url to the individual congress person's website? How can I pull that url from the API? Is there another endpoint that gives the url for each congress person's website? Thanks.

**Comment by rbram** [comment]
Hello. Thanks for your question. You cannot currently do this from the Congress.gov API. Here is a [link](https://github.com/LibraryOfCongress/api.congress.gov/blob/main/Documentation/MemberEndpoint.md) to the documentation related to the member endpoint.
