### ISSUE TITLE
More than one copy of a bill; `9hr77`.

### ISSUE THREAD

**Issue by c4lliope** [LibraryOfCongress/api.congress.gov#161]
```
{
    "error": "get() returned more than one Bill -- it returned 2! (MultipleObjectsReturned)",
    "request": {
        "billNumber": "77",
        "billType": "hr",
        "congress": "9",
        "contentType": "application/json",
        "format": "json"
    }
}
```

**Comment by rbram** [comment]
Hello. In earlier Congresses, such as those of the late 18th and early 19th centuries, there will be instances where bill numbering is not clear or evident. At this point in time, Congressional staff had not yet standardized how bills get numbered. Thus, there are instances where two legitimate bills have been assigned the same number. To make a distinction between the first session-introduced bill and the second session-introduced bill we add the “introduction date” to the URLs for these bills on Congress.gov. However, this distinction is not evident when returning data within the Congress.gov API. We will create a ticket to investigate how to accommodate these types of bills and provide an update on our findings and fixes soon. Please refer to the change log in coming weeks for updates on this.

**Comment by c4lliope** [comment]
Bypassed:
c4lliope [pushed](https://base.bingo/code/reap/compare/5534a0be3753b5064d30e1a8d3c684c9c16fb8c7...57bb61e541d50add1a8eb1a34f43a3580ef8381d) 1 commit to branch main.

* Pass on errored bills. ([57bb61e541d](https://base.bingo/code/reap/commit/57bb61e541d50add1a8eb1a34f43a3580ef8381d))

> https://labori.us/#narrow/stream/3-code/topic/reap.20.2F.20main
