### ISSUE TITLE
Recent `ENOTFOUND` errors

### ISSUE THREAD

**Issue by ryparker** [LibraryOfCongress/api.congress.gov#163]
Update: see DNS configuration issues found on api.congress.gov: https://github.com/LibraryOfCongress/api.congress.gov/issues/163#issuecomment-1788128819

---

I've recently been experiencing `ENOTFOUND` errors when requesting different APIs. It's not consistent but it seems to randomly occur on any API. I've noticed the error come up once every 10-20 minutes when chaining requests. It seemed to start happening about a week ago. Has anyone else noticed this?

In the most recent instance I was requesting:
`https://api.congress.gov/v3/committee-report/118/hrpt/97/text?api_key=<API_KEY>&format=json&limit=250&offset=0`

Request error:
```
cause: Error: getaddrinfo ENOTFOUND api.congress.gov
      at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:108:26) {
    errno: -3008,
    code: 'ENOTFOUND',
    syscall: 'getaddrinfo',
    hostname: 'api.congress.gov'
  }
```

I'm within the rate limit as you can see from my last request which had the following response headers:
```
 "x-ratelimit-limit": "1000",
  "x-ratelimit-remaining": "621",
```

Here's a list of other URLs where i've experienced this issue:
```
https://api.congress.gov/v3/nomination/118?api_key=<API_KEY>&format=json&limit=250&offset=1000
https://api.congress.gov/v3/committee-meeting/118?api_key=<API_KEY>&format=json
https://api.congress.gov/v3/committee-report/118/hrpt?api_key=<API_KEY>&format=json
https://api.congress.gov/v3/member?api_key=<API_KEY>&format=json
```

**Comment by rbram** [comment]
Hello. Thanks for your feedback. We have not been able to replicate this issue, but we will keep an eye on it.

**Comment by ryparker** [comment]
Thanks. I'll keep testing to see if its on my end.

**Comment by ryparker** [comment]
I keep running into this issue randomly on any api.congress.gov endpoint. Could it be due to api.congress.gov having invalid DNS configuration? See this repot I generated from: https://mxtoolbox.com/emailhealth/api.congress.gov/

![CleanShot 2023-10-31 at 17 33 55](https://github.com/LibraryOfCongress/api.congress.gov/assets/17558268/b030f46d-4028-4b7d-96ca-bdab5d1ac7e4)

**Comment by mnewatloc** [comment]
We're investigating this issue and have opened a bug ticket.

**Comment by mnewatloc** [comment]
Is this still occurring?

**Comment by ryparker** [comment]
I've not noticed this issue since January. I believe this can be closed. Thanks for the fix!
