### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by mirandar9936** [LibraryOfCongress/api.congress.gov#164]
Hello, I am not a professional software developer but I still need to get info from this API. To get the next results of data from the member endpoint, the pagination member gives me this url: https://api.congress.gov/v3/member?offset=20&limit=20&format=json?

When I use this url I get an error saying that the API key is missing. How do I form a url that includes the API key plus the query string parameters?  

Sorry, just learning, hopefully someone can help me.

**Comment by ryparker** [comment]
You can add the API key to the URL like so, just replace `<API_KEY>` with your key:

`https://api.congress.gov/v3/member?api_key=<API_KEY>&offset=20&limit=20&format=json`

I've also published a Postman collection with some of the basic requests. It hasn't been updated in some time but you may find it useful: https://documenter.getpostman.com/view/6803158/VV56LCkZ#intro

**Comment by mirandar9936** [comment]
Thank you!
