### ISSUE TITLE
Members of Congress and the Committees they belong to

### ISSUE THREAD

**Issue by mirandar9936** [LibraryOfCongress/api.congress.gov#165]
Hello, I am trying to compile a spreadsheet containing the current members of congress and the committees they belong too. While the member endpoint has lots of information for each member of congress, it does not provide the committees that each member belongs to. Where can I get this information? I need to associate each member of congress with all the committees they belong to.

**Comment by rbram** [comment]
Hello. Thanks for your question. Please consult the following pages for current members and their committee assignments:

Senate: https://www.senate.gov/general/committee_assignments/assignments.htm
House: https://clerk.house.gov/members/#MemberProfiles

**Comment by mirandar9936** [comment]
Thanks. How can I automate getting the above information through the API using code? I would rather not have to go one by one for each congress person. Is there an endpoint that will give this info back in JSON?

**Comment by Gmanicus** [comment]
https://github.com/unitedstates/congress-legislators Might have what you're looking for

**Comment by mirandar9936** [comment]
Thanks!

**Comment by asebold** [comment]
@mirandar9936 Not sure if you still need this, but after some digging, I found automated sources for this data in XML:

House: [https://clerk.house.gov/xml/lists/MemberData.xml](https://clerk.house.gov/xml/lists/MemberData.xml)
Documentation for House XML: [https://clerk.house.gov/member_info/MemberData_UserGuide.pdf](https://clerk.house.gov/member_info/MemberData_UserGuide.pdf)

Senate: [https://www.senate.gov/general/committee_membership/committee_memberships_SSAP.xml](https://www.senate.gov/general/committee_membership/committee_memberships_SSAP.xml)
