### ISSUE TITLE
Error on `/bill/6/cen_doc_h/73/actions`: unknown resource.

### ISSUE THREAD

**Issue by c4lliope** [LibraryOfCongress/api.congress.gov#169]
There is an uncommon bill in the 6th congress named `6 cen_doc_h 73`.
During a scraping run using:
https://base.bingo/code/reap/src/branch/main/congress.process.rb

I came across a number of errors I need to manually bypass:
```bash
2023-10-28T17:39:26+00:00:      Pulling session/6/bill/cen_doc_h73.2023-07-06T17-55-26Z
                                .0; actions.0Error: Code # 404
"{\n    \"error\": \"Unknown resource: bill/6/cen_doc_h/73/actions\"\n}"
Error: Code # 404
"{\n    \"error\": \"Unknown resource: bill/6/cen_doc_h/73/actions\"\n}"
Error: Code # 404
"{\n    \"error\": \"Unknown resource: bill/6/cen_doc_h/73/actions\"\n}"
Error: Code # 404
"{\n    \"error\": \"Unknown resource: bill/6/cen_doc_h/73/actions\"\n}"
Error: Code # 404
"{\n    \"error\": \"Unknown resource: bill/6/cen_doc_h/73/actions\"\n}"
Error: Code # 404
"{\n    \"error\": \"Unknown resource: bill/6/cen_doc_h/73/actions\"\n}"
Error: Code # 404
"{\n    \"error\": \"Unknown resource: bill/6/cen_doc_h/73/actions\"\n}"
undefined method `code' for nil:NilClass

From: /root/reap/lib/congress.rb:84 Congress#query_address:

    79:     end
    80:
    81:     response
    82:   rescue => e
    83:     STDERR.puts e
 => 84:     binding.pry
    85:   end
    86:
    87:   def page_loop address, key, body
    88:     measures = []
    89:     begin

[1] pry(#<Congress>)>
```

I decided to bail from my retry loop and accept the error json, upon seeing any 404 errors... though this kicks the problem through to be handled in the application layer someday.

**Comment by Gmanicus** [comment]
Got curious and did some poking around. I remembered that, somewhat recently, using lowercase types in the API requests was deprecated. It looks like it wants to return something when requesting
`bill/6/CEN_DOC_H/73`, but hits an error
```
Reverse for 'bill_committees' with keyword arguments... not found...
```
`bill/6/CEN_DOC_H/73/actions` interestingly enough still returns "Unknown resource". Probably has something to do with the previous error.
