### ISSUE TITLE
im not recieving my API key, 

### ISSUE THREAD

**Issue by b1tburn3r20** [LibraryOfCongress/api.congress.gov#172]
I requested on a couple different emails because it wasnt working but still nothing, not even in my spam folder
emails: alejandrojosuebermudez@gmail.com, ajbermudez125@gmail.com

**Comment by Gmanicus** [comment]
Just tested with one of my backup email addresses. Moments after hitting 'Signup', I had received a new API key. Did you try copy-pasting the email address just to make sure there wasn't a typo somewhere?

**Comment by jonquandt** [comment]
I just created an issue for the api.data.gov team to look at, since the API keys are generated/maintained by that shared service.

They're really great, so should be able to help!

**Comment by jonquandt** [comment]
@b1tburn3r20 - please try creating a key again. There was a temporary issue in delivery of API keys from the service. 
https://github.com/18F/api.data.gov/issues/670#issuecomment-1808407109

**Comment by b1tburn3r20** [comment]
Thank you for the responses, yes it works now. At the time I tested it with 3 different emails, and had family try from other network locations and addresses. It must have been a bug. Thanks!
