### ISSUE TITLE
Many committee meeting documents are not viewable

### ISSUE THREAD

**Issue by Gmanicus** [LibraryOfCongress/api.congress.gov#174]
Hello,

Attempting to view many committee meeting PDF documents yields an error. It looks like the PDF document exists and the page loads just fine, but the PDF document itself encounters some sort of error when loading.

Here are some of the problem documents I have found so far:
- https://www.congress.gov/118/meeting/house/116397/documents/BILLS-118-NA-B001296-Amdt-1.pdf
- https://www.congress.gov/118/meeting/house/116397/documents/BILLS-118-NA-H001038-Amdt-3.pdf
- https://www.congress.gov/118/meeting/house/116397/documents/BILLS-118-NA-K000380-Amdt-6.pdf
- https://www.congress.gov/118/meeting/house/116397/documents/BILLS-118-NA-O000173-Amdt-11.pdf
- https://www.congress.gov/118/meeting/house/116428/documents/BILLS-118-HR4531-N000002-Amdt-2.pdf
- https://www.congress.gov/118/meeting/house/116428/documents/BILLS-118HR4531ih-U4.pdf
- https://www.congress.gov/118/meeting/house/116486/documents/CRPT-118-FA00-Vote001-20231019-U1.pdf
- https://www.congress.gov/118/meeting/house/116549/documents/CRPT-118-WM00-Vote004-20231102.pdf
- https://www.congress.gov/118/meeting/house/116263/documents/CRPT-118-SM00-Vote004-20230718.pdf
- https://www.congress.gov/118/meeting/house/115466/documents/HMKP-118-IF16-Transcript-20230308.pdf

**Comment by rbram** [comment]
Hello. Thanks for your feedback. We will create a ticket for this.

**Comment by Gmanicus** [comment]
All of these documents appear to be loading just fine now. I will reopen this issue if the problem appears to come back.
