### ISSUE TITLE
Missing names for committee meeting documents

### ISSUE THREAD

**Issue by Gmanicus** [LibraryOfCongress/api.congress.gov#175]
Hello,

I am unsure if this is decided by Congress.gov or whoever submits these documents, but many committee documents either don't have a `name` field at all, or the name doesn't match what can be seen in the document. This makes it difficult or impossible to determine the subject of the document programmatically.

For example, `https://api.congress.gov/v3/committee-meeting/118/house/116397`
This was a meeting held by the House Budget Committee on 9/20/2023 to mark up a concurrent resolution on the budget for 2024.
- Most of the attached documents lack a `name` field
- The names that do exist are odd and not all unique. For example: "The Honorable Brendan F. Boyle" is the name given for Amendment 1 & 2 on the H. Con. Res. It would be more optimal if these were something like: 'Boyle Amendment # 1', 'Boyle Amendment # 2'

I understand if this is outside of Congress.gov's control. I just wanted to bring it to your attention in case this can be fixed or improved upon.

**Comment by b1tburn3r20** [comment]
did they email you your api key? they arent for me

**Comment by Gmanicus** [comment]
@b1tburn3r20 Yep, I've had a key for months. Never had a problem. They'll likely get back to you on your issue tomorrow.

**Comment by rbram** [comment]
Hello. Thanks for your feedback. We will share your comments with developers of the House Committee Repository that is Congress.gov’s data source for the data you brought to our attention.

**Comment by Gmanicus** [comment]
Thanks! In that case, I will close this issue. I appreciate it.
