### ISSUE TITLE
Add amendment text to the API

### ISSUE THREAD

**Issue by aweiss27** [LibraryOfCongress/api.congress.gov#18]
Add amendment text to the API. 

Amendment text is sourced from the Congressional Record. This is blocked by upstream development involving better associating the related article in the Congressional Record to the amendment.

**Comment by toddfries** [comment]
Hmm, seems odd, the data is clearly available, as the website can display it. Wonder if programatic hoops could get this done until better upstream response happens?  I would hate for people to have to resort to scraping your website to get the contents of an amendment ...

**Comment by rbram** [comment]
Hello, there are several complexities to this issue. First, Congress.gov is able to consume submitted Senate amendment text from the Congressional Record only for the 117th Congress onwards (that text from the Congressional Record is then embedded on the text tab of those amendments). Second, prior to the 117th Congress for Senate amendments and for all House amendments, Congress.gov only has a Congressional Record page range for where the text is located in the record. Congress.gov does use some front-end logic to embed that text in certain limited cases. In the future, depending on the type of amendment and Congress, we plan to release either return the amendment text or the Congressional Record page range in the API.

**Comment by InfiniteCodeMonkeys** [comment]
Can this be added for the 118th Congress onwards with the understanding that amendments for prior congresses won't be available?

**Comment by mnewatloc** [comment]
Thanks for your input. We will discuss this at our next operational meeting.
