### ISSUE TITLE
/committee/{chamber}/{committeeCode} only works for subcommittees

### ISSUE THREAD

**Issue by Narlotl** [LibraryOfCongress/api.congress.gov#180]
The response for the Education and the Workforce Committee (`/committee/house/hsed00`), which has no parent is
```json
{
    "error": "'NoneType' object has no attribute 'in_current_congress' (AttributeError)",
    "request": {
        "chamber": "house",
        "contentType": "application/json",
        "format": "json",
        "systemCode": "hsed00"
    }
}
```
The response for the Workforce Protections Subcommittee (`/committee/house/hsed10`) has a response
```json
{
    "committee": {
        "bills": {
            "count": 1177,
            "url": "https://api.congress.gov/v3/committee/house/hsed10/bills?format=json"
        }
        ...
    }
}
```
<br>
This result is consistent across all committees in Congress 118, if it has a parent, the status is 200, otherwise it's 500.

**Comment by rbram** [comment]
Hello. Thanks for your feedback. We have replicated this issue and have created a bug ticket to fix it. Please monitor the change log for updates on this.
