### ISSUE TITLE
"Related bills" and bill versions on Congress.gov

### ISSUE THREAD

**Issue by DanielSchuman** [LibraryOfCongress/api.congress.gov#184]
Congress.gov's helpful new "related bills" feature is apparently intended to indicate when legislation related to the bill viewed on Congress.gov is included in that bill. For example, when viewing omnibus bill H.R. 1234 on Congress.gov, if the bill you are viewing includes the text from H.R. 444 and H.R. 555, those bills should be identified in the "related bills" tab.

Looking at the recently enacted National Defense Authorization Act for Fiscal Year 2024 (H.R. 2670) I found an unexpected result.

The "Related Bills" tab identifies 180 related bills, including: 
- Disclosing Foreign Influence in Lobbying Act (H.R. 1190, S. 829)
- Lobbying Disclosure Improvement Act (H.R. 4041, S. 264)

This suggests that provisions of these bills, or something similar, have been identified as being incorporated, in whole or in part, to a greater or lesser degree, in the NDAA bill being reviewed on Congress.gov.

However, if you look at the enrolled bill, those provisions are not present.

What happened? According to [this article](https://www.insidepoliticallaw.com/2023/12/07/congress-removes-foreign-agents-registration-act-fara-related-provisions-from-final-ndaa/), those provisions were stripped from the enrolled version even though they were present in the version that passed the senate.

That appears to be the case. I did not find the provisions in the [enrolled NDAA](https://www.congress.gov/bill/118th-congress/house-bill/2670/text) but I did find them in the [engrossed Senate amendment](https://www.congress.gov/bill/118th-congress/house-bill/2670/text/eas) in Title LXXI.

When identifying related legislation, Congress.gov should consider: (1) displaying the related legislation for each versions of that bill (e.g. introduced, reported, engrossed, enrolled); or (2) displaying the related legislation for the final stage of the legislation.

With those choices, the second option ("the final stage") would be more confusing, as legislation that has not advanced to enactment may have enrolled bills in both chambers, or they've both been reported by committee, etc. 

I think the better solution would be to display to the user the version of the bill upon which related bills are identified, and give the user the option to toggle between different versions of the bill to see related legislation, or to "select all" to see related legislation connected to any version of the bill.

**Comment by mnewatloc** [comment]
Thank you for reaching out. We have put your suggestion into our Feedback Repository.
