### ISSUE TITLE
Constititonal Authority Statements missing from bill endpoint

### ISSUE THREAD

**Issue by TeepTech** [LibraryOfCongress/api.congress.gov#191]
I am evaluating constitutional authority statements (CAS) and am finding that for the 118th congress the constitutionalAuthorityStatementText element is missing from the bill endpoint even though a CAS exists in the congressional record.  This is also reflected on the website which is more useful for demonstration.  I've included an example from my Representative, Andy Kim.  In total this issue impacts 12 of the 20 bills he sponsored.

The following image shows a search on the site for HR6154.  It does not have a CAS link under "More on this bill".  Neither is the constitutionalAuthorityStatementText element found in the bill end point for this bill (and others that I have spot checked)
![Fig 2 - Bill6154Leg](https://github.com/LibraryOfCongress/api.congress.gov/assets/157251267/51a11991-7aa7-4ea0-a9e4-2c427df4fa91)

The following is the website search result with the both the legislature and congressional record boxes checked establishing the existence of the CAS
![6154leg-conrec](https://github.com/LibraryOfCongress/api.congress.gov/assets/157251267/f9ea005c-ad11-46fe-917d-bbfd7c686b53)

The following is the text of the CAS found at the congressional record link and the text is similar in form and content to others from this Rep.
![SiteSnipBill6154LegCongRec](https://github.com/LibraryOfCongress/api.congress.gov/assets/157251267/89c9cdf6-f2fc-40ee-ab11-f8392fbf22f4)

**Comment by mnewatloc** [comment]
Thanks for your feedback. We already have a ticket to fix this and it will be in an upcoming release.

**Comment by TeepTech** [comment]
Thank you for the quick response.  Is the release and its timing known at this point?  Is there a straight forward work around (I saw no easy way to find the associated congressional record entry)?

**Comment by rbram** [comment]
Hello. Could you please let us know if Constitutional Authority Statements are appearing now? Thanks.

**Comment by rbram** [comment]
Hello. We have a ticket created for the permanent fix and will let you know when it is fixed.

**Comment by apreiter18** [comment]
This issue was fixed. An example: https://api.congress.gov/v3/bill/118/hr/6154?api_key=[INSERT_KEY]

**Comment by TeepTech** [comment]
Thank you!

Sent with [Proton Mail](https://proton.me/) secure email.
