### ISSUE TITLE
committee endpoint broken

### ISSUE THREAD

**Issue by jermatic** [LibraryOfCongress/api.congress.gov#195]
https://api.congress.gov/v3/committee/senate/ssva00

{
    "error": "'NoneType' object has no attribute 'in_current_congress' (AttributeError)",
    "request": {
        "chamber": "senate",
        "contentType": "application/json",
        "format": "json",
        "systemCode": "ssva00"
    }
}

**Comment by mnewatloc** [comment]
We already have a ticket for this and it should be fixed in our next release.

**Comment by apreiter18** [comment]
related to issue #180
