### ISSUE TITLE
*SERIOUS* API key proper usage unclear.

### ISSUE THREAD

**Issue by HopeTS** [LibraryOfCongress/api.congress.gov#197]
In the API docs [here](https://gpo.congress.gov/#/bill/bill_titles) the api_key is sent in the query string. However in the repo it says not to do that.

**Comment by rbram** [comment]
Hello. Thanks for your feedback. We have updated our documentation here: https://github.com/LibraryOfCongress/api.congress.gov/tree/main/api_client
