### ISSUE TITLE
If I essentially want to download the archive of daily congressional records, does the API allow you to go all the way back in time?

### ISSUE THREAD

**Issue by ktshieh** [LibraryOfCongress/api.congress.gov#200]
Hello, I'm looking to do a bulk download of the Daily Congressional Record issues — is this possible with the API? 
Thank you!

**Comment by Gmanicus** [comment]
I believe I can answer this question for you. Congress.gov has a [Coverage Dates section](https://www.congress.gov/help/coverage-dates). They state that the coverage for the daily congressional record starts from 1995, or the 104th Congress.

**Comment by ktshieh** [comment]
Thanks for the quick response! Does that imply that one can programmatically retrieve Daily Congressional Record issues in bulk via the API? For instance, I did not see anything in the documentation about specifying a time range and then retrieving all of the issues for that time range, but perhaps there's a workaround?
