### ISSUE TITLE
List Bills updateDate is constantly updated on old records and List Committees between dates api call not working

### ISSUE THREAD

**Issue by leemgilliam711** [LibraryOfCongress/api.congress.gov#201]
The updateDate on the Bill record is being constantly updated. The curl command below which asks for all bills that have updated between 9am and 3pm UTC ( fromDateTime=2024-02-20T9:00:00Z,    toDateTime=2024-02-20T15:00:00Z ) return 3595 total bills, many which are from congress' from years ago. This has been happening for roughly 1 week.

curl -X GET "https://api.congress.gov/v3/bill?fromDateTime=2024-02-20T9:00:00Z&toDateTime=2024-02-20T15:00:00Z&sort=updateDate+desc&offset=20&limit=20&format=json&api_key=API_KEY_HERE" -H "accept: application/xml"

The List Committees endpoint throws an error when including "fromDateTime" and "toDateTime" parameters.

curl -X GET "https://api.congress.gov/v3/committee?format=json&fromDateTime=2024-02-20T9:00:00Z&toDateTime=2024-02-20T15:00:00Z&api_key=API_KEY_HERE" -H "accept: application/xml"

Response:
```
{
  "error": "cannot access local variable 'result' where it is not associated with a value (UnboundLocalError)",
  "request": {
    "contentType": "application/json",
    "format": "json"
  }
}
```

You receive the same issues when making test api calls through the [https://api.congress.gov/](https://api.congress.gov/) UI.

**Comment by ryparker** [comment]
I notice this as well, even though I pull the legislation from govInfo I believe the updateDate is the same. I too am curious why so many legislation are being updated on a daily bases. Are there actual changes in these updates?

**Comment by leemgilliam711** [comment]
@rbram Do you have an update on whether this has been fixed or when this will be fixed?

**Comment by rbram** [comment]
Hello. At this time we do not have a time frame but we are estimating that this will be resolved in Summer 2024.
