### ISSUE TITLE
Request endpoint for accessing the Congressional Research Service reports

### ISSUE THREAD

**Issue by Jared-Kirschbaum** [LibraryOfCongress/api.congress.gov#204]
I cant seem to find where to access these records in either this API or the gov info api, the location for these records are located here:
https://crsreports.congress.gov/

**Comment by apreiter18** [comment]
related to #19

**Comment by mnewatloc** [comment]
Thank you for reaching out. At this time, CRS reports are not available in the Congress.gov API. We have an open request for incorporating these into the API and you can view that information here: https://github.com/LibraryOfCongress/api.congress.gov/issues/19

**Comment by Jared-Kirschbaum** [comment]
Are they available on any other API that you know of? It looks like that request has been open for almost a year

**Comment by apreiter18** [comment]
CRS reports are currently not available on any API that we are aware of. Relevant updates will be published in issue #19. Thanks!
