### ISSUE TITLE
Bill Actions Roll Call Vote Link Error

### ISSUE THREAD

**Issue by leemgilliam711** [LibraryOfCongress/api.congress.gov#210]
When the bill actions list item includes a link to the corresponding Clerk House Roll Call Vote, the link it returns is invalid. Here's an example:

Bill endpoints endpoint: "v3/bill/118/hres/1071/actions"
Returned Clerk House Roll Call Vote Endpoint: "https://clerk.house.gov/evs/2024/roll81.xml". (Broken)

Working Clerk House Roll Call Vote Endpoint: "https://clerk.house.gov/evs/2024/roll081.xml"

The Roll Call Vote endpoint is missing a "0"; "/roll81.xml" vs "roll081.xml".

**Comment by rbram** [comment]
Hello. Thanks for your feedback. We have created a ticket to fix this.
