### ISSUE TITLE
Where to place amendment actions in the bill action list

### ISSUE THREAD

**Issue by avalatea** [LibraryOfCongress/api.congress.gov#226]
Hi! Might end up being more of a question than an issue, but I noticed that congress.gov includes amendment actions at strategic points (sample: [HR2882](https://www.congress.gov/bill/118th-congress/house-bill/2882/all-actions))

<img width="800" alt="Screenshot 2024-04-10 at 10 48 29 AM" src="https://github.com/LibraryOfCongress/api.congress.gov/assets/107426303/ba68ef99-0aab-42fb-b341-097b73a41a60">

However, the `/bill/{congress}/{billType}/{billNumber}/actions` endpoint does not have this information by itself ([HR2882](https://api.congress.gov/v3/bill/118/hr/2882/actions?limit=250&api_key=DEMO_KEY))

<img width="800" alt="Screenshot 2024-04-10 at 10 48 00 AM" src="https://github.com/LibraryOfCongress/api.congress.gov/assets/107426303/db9fa27a-8d36-4fa7-95c7-b35ddfcdc7c2">

I am fairly certain that the actions list in congress.gov comes from composing the amendment actions with the bill actions. However, I am unsure how the system can place the order correctly, especially when so many actions fall on 03/23/2024. How do you guys do this? Can the bill endpoint be updated to also include the amendment actions?

**Comment by rbram** [comment]
Thank you for reaching out. You are correct that “bill actions” and “amendment actions” are two distinct entities that are concatenated in Congress.gov. Currently, the Congress.gov API doesn’t support displaying both amendment actions and bill actions in the bill actions endpoint. We will add this to our “possible future development” milestone.

**Comment by avalatea** [comment]
@rbram Thank you for your thoughts. Do you happen to know how congress.gov orders these two different sets of actions when displayed on the congress.gov website?

**Comment by rbram** [comment]
On Congress.gov, actions are ordered by date/time with the newest action displaying first by default. Users have the ability to sort by “oldest action first,” as well. 

For example, if “Action 1” was on 4/10/2024 at 9:00am with the and “Action 2” was on 4/10/2024 at 9:55am, the following list would be how they display by default:
•	4/10/2024 Action 2
•	4/10/2024 Action 1
If you add a third action to the list (let’s call it “Amendment Action” that was dated 4/10/2024 at 9:32 am), the list would be:
•	4/10/2024 Action 2
•	4/10/2024 Amendment Action
•	4/10/2024 Action 1

Here is an example: https://www.congress.gov/bill/118th-congress/house-bill/2882/all-actions?s=4&r=1

**Comment by avalatea** [comment]
Ahh, thank you! What would be the best way to get the datetime information?

**Comment by apreiter18** [comment]
The [/amendment/{congress}/{amendmentType}/{amendmentNumber}/actions](https://api.congress.gov/#/amendments/Amendmentactions) endpoint provides specific dates for amendments actions. We will discuss the feasibility of adding time to these with our developers. Thanks. 

An example: https://api.congress.gov/v3/amendment/117/samdt/2137/actions?api_key=
