### ISSUE TITLE
New element with conditional URLs

### ISSUE THREAD

**Issue by apreiter18** [LibraryOfCongress/api.congress.gov#227]
Add a new API element (starting with the bill endpoint) that provides users with a conditional Congress.gov URL. 

e.g., for HR 117 HR 3076
/bill/117/hr/3076
so that a user can add "congress.gov" before "/bill" and be provided a URL to the Congress.gov webapp.

**Comment by Gmanicus** [comment]
☝️ That actually already works. If you use the URL `congress.gov/bill/117/hr/3076`, it will auto-resolve to https://www.congress.gov/bill/117th-congress/house-bill/3076
