### ISSUE TITLE
Hey congressional bills for social issues , data read type is what I want, please pass me.

### ISSUE THREAD

**Issue by Stromlight** [LibraryOfCongress/api.congress.gov#239]
I was searching a congressional social bills data .now I like to search harm from social media in data.

**Comment by Gmanicus** [comment]
The Bill Details endpoint has a `policyArea` field ([potential values listed here](https://www.congress.gov/help/field-values/policy-area)). Is that what you're looking for?

GovTrack.us might also be able to help you: https://www.govtrack.us/congress/bills/subjects/social_welfare

**Comment by apreiter18** [comment]
Hello- I hope I am understanding your question correctly, please let me know if I am not. If you are looking for policy areas, the [Bill Details endpoint](https://api.congress.gov/#/bill/bill_details) has a `policyArea` field. Every bill and resolution is assigned one policy area term out of a controlled [field values list](https://www.congress.gov/help/field-values/policy-area) available on Congress.gov. Read more [about policy area terms](https://www.congress.gov/help/legislative-glossary#glossary_policyareaterm) on Congress.gov.

Additionally, you can return a list of subjects using this endpoint: /bill/{congress}/{billType}/{billNumber}/subjects
This will return all subjects associated with a particular piece of legislation. 

Lastly, while this is not an API resource, you can search by policy area and/or legislative subject terms on [Congress.gov Advanced Search](https://www.congress.gov/advanced-search/legislation#scrollNav-5).

**Comment by Stromlight** [comment]
Thank you this is very helpful.

**Comment by Stromlight** [comment]
and you can continue on request.

**Comment by Stromlight** [comment]
Can we further share something I like to get data from social media in a harm to society and nation.like sexual activities , suicide, nude post , bad content , and so.
