### ISSUE TITLE
🎁  Postman collection

### ISSUE THREAD

**Issue by ryparker** [LibraryOfCongress/api.congress.gov#24]
I created a [Postman collection](https://documenter.getpostman.com/view/6803158/VV56LCkZ) for the community. I can transfer it over to your team if you'd like to host it yourself. Otherwise I'll create a public repo so that the community can maintain it if they want.

Thanks for making the new API open to the public 😄

**Comment by rbram** [comment]
Thank you. We will take a look at this.
