### ISSUE TITLE
GovInfo bill data more than 2 weeks out of date

### ISSUE THREAD

**Issue by danielmroberts** [LibraryOfCongress/api.congress.gov#240]
I am posting here because I have not been able to get a response from GovInfo. They have not responded to my support request or the github project issue I posted. Is their source of data the Congress.gov API?

No new House or Senate bills have been added to their data files since 4/18. Here is the issue I posted to their bulk data project with more details.
https://github.com/usgpo/bulk-data/issues/160

I would prefer not to start hitting the Congress.gov API unnecessarily.

**Comment by apreiter18** [comment]
It appears that GPO has answered your query on their GitHub so I am going to close this issue.
