### ISSUE TITLE
API rate limit tracking

### ISSUE THREAD

**Issue by apreiter18** [LibraryOfCongress/api.congress.gov#244]
Feedback from colleagues: 

"Has your team considered putting rate limit info (like rate limit and rate limit remaining) in the header returned from the API? Not critical to work on our end but it would simplify some of the tracking of the rate limit we are doing currently. "

**Comment by ryparker** [comment]
Isn't this already supported? Every request to api.congress.gov returns these two headers

```
X-Ratelimit-Limit: 5000
X-Ratelimit-Remaining: 4999
```

**Comment by apreiter18** [comment]
Thanks, @ryparker for this information and this reminder!

**Comment by ryparker** [comment]
Np!
