### ISSUE TITLE
Votes endpoint

### ISSUE THREAD

**Issue by c0nnortb** [LibraryOfCongress/api.congress.gov#245]
Would be nice to be able to get vote data from the API. Any plans to do so?

**Comment by apreiter18** [comment]
The Congress.gov team is in the early stages of investigating the feasibility of 1.) incorporating vote data into Congress.gov and 2.) creating a Vote endpoint in the Congress.gov API. We are currently working towards having a better understanding of what this will entail. While we currently do not have a timeline, we are hopeful to have more information at a later date. Please see issue #64 for updates related to this work. Thanks!
