### ISSUE TITLE
(congress): inaccurate `endYear`

### ISSUE THREAD

**Issue by ryparker** [LibraryOfCongress/api.congress.gov#256]
In the congress API, the `endYear` value is inaccurate for some of the congresses. Here is an incomplete list of congresses i've found errors in:

```
110
112
113
114
115
116
117
118
```

For example request the 117th congress:
```sh
curl 'https://api.congress.gov/v3/congress/117?format=json&api_key=<API_KEY>' 
```

Response
```json
{
    "congress": {
        "endYear": "2022",
        "name": "117th Congress",
        "number": 117,
        "sessions": [
            {
                "chamber": "House of Representatives",
                "endDate": "2022-01-03",
                "number": 1,
                "startDate": "2021-01-03",
                "type": "R"
            },
            {
                "chamber": "Senate",
                "endDate": "2022-01-03",
                "number": 1,
                "startDate": "2021-01-03",
                "type": "R"
            },
            {
                "chamber": "House of Representatives",
                "endDate": "2023-01-03",
                "number": 2,
                "startDate": "2022-01-03",
                "type": "R"
            },
            {
                "chamber": "Senate",
                "endDate": "2023-01-03",
                "number": 2,
                "startDate": "2022-01-03",
                "type": "R"
            }
        ],
        "startYear": "2021",
        "updateDate": "2021-01-12T20:05:52Z",
        "url": "https://api.congress.gov/v3/congress/117?format=json"
    },
    "request": {
        "congress": "117",
        "contentType": "application/json",
        "format": "json"
    }
}
```

Notice how the `endYear` is set to `2022`, but the 2nd sessions end on `2023-01-03`. I had expected the `endYear` to be `2023`.

**Comment by apreiter18** [comment]
Hi @ryparker - we updated the documentation for the Congress endpoint to account for your question. Thank you for the feedback. Here is some information:

<endYear> (e.g. 2020) 
- The generalized end year for the congress. Congresses span over a two-year period. See [Congresses - Field Values](https://www.congress.gov/help/field-values/congresses) for more information about congress field values.  

<endDate> (e.g. 2020-01-03)
- The specific end date of the session. This value is specified for legislative research. See [Past Days in Session](https://www.congress.gov/past-days-in-session) for more information about past days in session of legislative sessions.
