### ISSUE TITLE
502 error for getting members by congress, state, and district

### ISSUE THREAD

**Issue by bendur** [LibraryOfCongress/api.congress.gov#257]
Calling the new [GET /member/congress/:congress/:stateCode/:district](https://api.congress.gov/#/member/member_list_by_congress_state_district) method results in a 502 error. 

I've tried on the documentation page above and using curl.

**Comment by apreiter18** [comment]
Thanks, @bendur - we are investigating this error message.

**Comment by pcwa-ahendricks** [comment]
Is there a workaround for this?
