### ISSUE TITLE
pagination URL is incorrect

### ISSUE THREAD

**Issue by moonshiner** [LibraryOfCongress/api.congress.gov#26]
when I call the API   https://api.congress.gov/v3/member

it returns the first set of values, and the 'pagination' object like so:

{'count': 2431, 'next': 'https://api.data.gov/congress/v3/member?offset=20&limit=20&format=json'}

replace https://api.data.gov/congress/v3/member with   https://api.congress.gov/v3/member

**Comment by rbram** [comment]
Thank you for your feedback. Our developers are working on this.

**Comment by mnewatloc** [comment]
We've added this to our near-term backlog. Check the [changelog](https://github.com/LibraryOfCongress/api.congress.gov/blob/main/ChangeLog.md
) for updates.

**Comment by moonshiner** [comment]
Thanks I've implemented a workaround with a simple string replace but thanks!

**Comment by adolph** [comment]
Workaround, where _member.ndjson_ is a file appended with body output from an http client using variable _url_:

**Raw, API key unauth error:**
$ url="$(jq '.pagination.next' member.ndjson | tr -d '"' | tail -n1)"; echo "$url"
https://api.data.gov/congress/v3/member?offset=60&limit=20&format=json

**Fixed, data returns:**
$ url="$(jq '.pagination.next' member.ndjson | sed -e 's;data.gov/congress;congress.gov;' | tr -d '"' | tail -n1)"; echo "$url"
https://api.congress.gov/v3/member?offset=60&limit=20&format=json

**Comment by rbram** [comment]
Hello. Thank you for your feedback. The pagination URLs should be fixed.

**Comment by BhinbahadurUK** [comment]
Add cipher to reiterate same action please
