### ISSUE TITLE
Bills' action dates/update dates not within fromDateTime - toDateTime range

### ISSUE THREAD

**Issue by sdxiang** [LibraryOfCongress/api.congress.gov#261]
The call

https://api.congress.gov/v3/bill/117?fromDateTime=2022-01-01T00:00:00Z&toDateTime=2022-01-31T23:59:59Z

returns 14 bills, but only one of them has an update date within the time range, and none of them has a latest action date within the time range. Not sure if this is a bug or if I'm just misunderstanding what it's filtering on?

**Comment by apreiter18** [comment]
Hi @sdxiang - the `<updateDate>` element is thedate of update on Congress.gov. This update date does not include updates to bill text. The `<updateDate>` is the date of the last update received for the legislative entity. It’s not a date corresponding to the legislative date or legislative action date. Hope this helps!

**Comment by sdxiang** [comment]
I think I'm still confused as to what date the API is filtering on-- for example, here is a bill returned by the original call, and there is no date within the specified time range (2022-01-01 through 2022-01-31).
![image](https://github.com/LibraryOfCongress/api.congress.gov/assets/140848819/827d9fef-4d98-4705-be0b-d414174a6e92)
I took a look at some of the bill endpoints linked in the response, and found that in most cases the only date within the time range is actually the first update date under "titles"
![image](https://github.com/LibraryOfCongress/api.congress.gov/assets/140848819/fc4d0e17-ca28-4ee3-affb-b4e786027d01)
What does this date mean?

**Comment by apreiter18** [comment]
Hi @sdxiang - please confirm or correct I am understanding you question correctly. When I perform this call https://api.congress.gov/v3/bill/117?fromDateTime=2022-01-01T00:00:00Z&toDateTime=2022-01-31T23:59:59Z&api_key=INSERT_KEY I get a list of bills that have `<updateDate>` elements within the time frame queried:

For example, SRes 469:
![image](https://github.com/LibraryOfCongress/api.congress.gov/assets/131792850/ea505ae7-d13a-4892-b9d8-cd42f45c5351)

The `<updateDate>` is the date of the last update received for the legislative entity. It’s not a date corresponding to the legislative date or legislative action date. The data partner can update this date and resend the information to Congress.gov at any time.  

HOWEVER, I do see your point, though, for certain bills not having a corresponding `<updateDate>` in the list level. For example, S 3206 has a 2023 date in the list-level but a 2022 date in the detail level (see: https://api.congress.gov/v3/bill/117/s/3206?format=xml&api_key=INSERT_KEY), which might explain why it is being returned in the query. 

I will submit a ticket to investigate this discrepancy. Thanks.

**Comment by sdxiang** [comment]
While the first bill returned does have an `<updateDate>` within the time frame queried, many of them do not, for example:

S 3206
![image](https://github.com/LibraryOfCongress/api.congress.gov/assets/140848819/84eb689e-fc9b-4e36-b976-c58e470985e1)

SRES 443
![image](https://github.com/LibraryOfCongress/api.congress.gov/assets/140848819/fe02eac6-9609-48f3-867a-80a3de14da1d)

S 4
![image](https://github.com/LibraryOfCongress/api.congress.gov/assets/140848819/bfb46db2-98f5-4285-8a2e-875b3980c3a9)

I think you're right that they're being returned because they have Jan 2022 update dates in the detail level but not the list level, and this is what's causing the confusion.

**Comment by apreiter18** [comment]
Ok a quick update as I investigate:

Currently, the list level (e.g., https://api.congress.gov/v3/bill/117?fromDateTime=2022-01-01T00:00:00Z&toDateTime=2022-01-31T23:59:59Z&api_key=DEMO_KEY) is returning the updateDateIncludingText date as just the <updateDate> in the list level. HOWEVER, users like this one, can query by <updateDate> which is returning any bill with a 2022 update date even if it is NOT present in the list level. 

For example, 117 S 3206 has this update date in the list level: <updateDate> 2023-01-02 </updateDate>

When I go look at the record in the detail level (https://api.congress.gov/v3/bill/117/s/3206?format=xml&api_key=DEMO_KEY) I see two dates:
 
![image](https://github.com/LibraryOfCongress/api.congress.gov/assets/131792850/8c73f3b5-e894-4326-a44a-7b9a76aebf6e)

So what I think is happening for these bills is in the list level <updateDate>= <updateDateIncludingText> in the detail level, which would explain why the bill is still being returned in the list level query you shared. 

Thank you for reporting this, @sdxiang - we will investigate further and updates will be posted in the change log.

**Comment by sdxiang** [comment]
Just wanted to flag that this list-level vs. detail-level `updateDate` issue seems to be affecting other endpoints as well:

The API documentation for the bound-congressional-record endpoint says that the response to `https://api.congress.gov/v3/bound-congressional-record?` should be sorted by most recent. However, when I make this query, the response does not seem to be sorted by either of the dates exposed (`date` or `updateDate`).

![image](https://github.com/LibraryOfCongress/api.congress.gov/assets/140848819/a8afe9dd-feaf-4222-ba57-7bb3182c52c0)

When I take a look at the individual records linked in the list response (e.g. `https://api.congress.gov/v3/bound-congressional-record/1943/1/6?`), it seems like some components have more recent update dates than others. For this example, the appendix has an `updateDate` of 2024-03-28 while the other sections have `updateDate`s of 2024-04-17, which is more consistent with this record's placement in the list response, but 2024-03-28 is the `updateDate` exposed for the entire record.

**Comment by ryparker** [comment]
@sdxiang reported the sorting issue here: https://github.com/LibraryOfCongress/api.congress.gov/issues/223

**Comment by apreiter18** [comment]
Good morning, @abdulrabbani00 . Thank you for the feedback. We maintain documentation [here](https://github.com/LibraryOfCongress/api.congress.gov/blob/main/Documentation/BillEndpoint.md) on the `<updateDate>` element. This is an important piece of information that does NOT correspond to any action date. Here is the language:

_"The date of update on Congress.gov. This update date does not include updates to bill text. The <updateDate> is the date of the last update received for the legislative entity . It’s not a date corresponding to the legislative date or legislative action date."_

Separately, we have an additional endpoint for `<updateDateIncludingText>`. The language for that element (also present in the Bill endpoint documentation is:

_"The date of update on Congress.gov, including if the update was to bill text.The <updateDate> is the date of the last update received for the legislative entity. It’s not a date corresponding to the legislative date or legislative action date."_

We plan to add both updateDate elements into the list level again. Please check the change log for updates on that. 

Regarding this enhancement request: "Perhaps another filter, which is lastActionDate. I think this is probably what most people want to know anyways." --> we will discuss the feasibility of this with our developers and report any updates in a G[it issue](https://github.com/LibraryOfCongress/api.congress.gov/issues/264) I created to track this request. Thanks!
