### ISSUE TITLE
117th congress members data inaccurate 

### ISSUE THREAD

**Issue by jacopo012** [LibraryOfCongress/api.congress.gov#263]
/member/congress/117 returns only 462 observations, but there should be 100 senators, 435 representatives and 6 non-voting delegates

**Comment by apreiter18** [comment]
@jacopo012 - I have a workaround for you that should return the correct number of members in the 117th Congress. 

https://api.congress.gov/v3/member/congress/117?currentMember=False&api_key=INSERT_KEY

Using the `currentMember=False` filter will return the total number (557) of members in the 117th Congress. This filter can be used on other Congresses, as well, to get the correct number. I hope this helps a bit. We will continue to work on improving the member endpoint in the meantime. Thanks!
