### ISSUE TITLE
QUESTION: how frequently is the Congress.gov.api updated? 

### ISSUE THREAD

**Issue by BrandonChiazza** [LibraryOfCongress/api.congress.gov#265]
I would like to know if this is perfectly in synch with Congress.Gov or if there are delays between information on congress.gov and what's available via this API?

**Comment by BrandonChiazza** [comment]
Thank you so much for the prompt respone @rbram . I have not found the details in the documentation regarding this, but will review. 

My question is pertaining to the dates in the bill documentation:  I noticed that in some cases there is a discrepancy for and the updateDate by a day or so. Is this expected? is there a reasoning here or some latecy between it being introduced physically, to its entry into congress.gov, and then another delay to the api?

Thank you in advance for your assistance. 
-Brandon

Definitions found from documentation below: 

-  (<updateDate> (e.g. 2021-06-07T20:24:30Z) The update date for the bill summary on Congress.gov. This may be the date the summary was published or re-published. The <updateDate> is the date of the last update received for the legislative entity . It’s not a date corresponding to the legislative date or legislative action date.
- <introducedDate>(e.g. 2021-05-11)The date the bill or resolution was submitted or introduced

**Comment by apreiter18** [comment]
Hello, @BrandonChiazza -  Congress.gov's legislation collection is updated the morning after a session adjourns. 

 Here is an example of a bill that was introduced yesterday and ingested into Congress.gov today (2024-07-16):

- HR 9030 on Congress.gov: https://www.congress.gov/bill/118th-congress/house-bill/9030?q=%7B%22search%22%3A%22chamberActionDateCode%3A%5C%222024-07-15%7C118%7C1000%5C%22+AND+billIsReserved%3A%5C%22N%5C%22%22%7D&s=4&r=1
- https://api.congress.gov/v3/bill/118/hr/9030?api_key=INSERT_KEY

The updateDate element can be best defined as the following: _the date of the last update received for the legislative entity . It’s not a date corresponding to the legislative date or legislative action date._

So you will see updateDate elements that differ from action dates.

**Comment by apreiter18** [comment]
Are you comfortable with closing this issue, @BrandonChiazza - or do you have any further questions? Thank you!

**Comment by BrandonChiazza** [comment]
Thank you. This was really helpful!

**Comment by BrandonChiazza** [comment]
I actually would like to just confirm my understanding further and ask a follow-up: 

- Congress.gov is updated once per day, the morning after the session adjourns. 
- Any activity throughout the day doesn't update throughout the day

Confirming that there are no additional synchs or updates throughout the day -- only one synch in the day. 

Thanks and sorry for the multiple questions here.

**Comment by apreiter18** [comment]
Hi @BrandonChiazza - Congress.gov has many collections so the updates can vary. For example,

1. Congress.gov's legislation collection (e.g., actions, official titles, cosponsors) is updated the morning after a session adjourns
2. Legislation texts, which come from the Government Publishing Office (GPO), are updated throughout the day, roughly 15 minutes after the legislation text becomes available on GPO's GovInfo website. 
3. Committee reports, which come from the Government Publishing Office (GPO), are updated throughout the day, roughly 15 minutes after the committee report becomes available on GPO's GovInfo website.  

This [chart](https://www.congress.gov/help/coverage-dates) shows when you can expect updates to occur on Congress.gov. 

I hope this helps a bit!

**Comment by apreiter18** [comment]
Hi @BrandonChiazza - I wanted to check in and see if this issue could be closed/or if you had any further questions. Thanks!
