### ISSUE TITLE
Naming inconsistency: committeeReport vs congressional-record

### ISSUE THREAD

**Issue by garethpotter** [LibraryOfCongress/api.congress.gov#27]
Any reason it’s `committeeReport` but `congressional-record` and `house-communication`? This feels inconsistent.

**Comment by rbram** [comment]
Thank you for your feedback. We will share this issue with our developers.

**Comment by mnewatloc** [comment]
We're considering this for future development. Check the [changelog](https://github.com/LibraryOfCongress/api.congress.gov/blob/main/ChangeLog.md) for updates.

**Comment by rbram** [comment]
Thanks for your feedback. We changed committeeReport to committee-report to make it more consistent with other endpoints. You can read more about other changes we made to the committee report API in the [Change Log](https://github.com/LibraryOfCongress/api.congress.gov/blob/main/ChangeLog.md#change-1-1).
