### ISSUE TITLE
Different xml and pdf versions for S797

### ISSUE THREAD

**Issue by avalatea** [LibraryOfCongress/api.congress.gov#270]
Hi. It looks like the xml and the pdf versions are different for the introduced bill version.

xml: https://www.congress.gov/118/bills/s797/BILLS-118s797is.xml
pdf: https://www.congress.gov/118/bills/s797/BILLS-118s797is.pdf

Is there a reason for this?

**Comment by apreiter18** [comment]
Thank you, @avalatea - we are investigating and will follow-up.

**Comment by apreiter18** [comment]
@avalatea - this has been resolved. See updated bill text versions here: 

- https://www.congress.gov/118/bills/s797/BILLS-118s797is.xml
- https://www.govinfo.gov/content/pkg/BILLS-118s797is/pdf/BILLS-118s797is.pdf

You may need to clear your browser cache, as well, to see the change.

**Comment by avalatea** [comment]
Ahh, it looks good! Thank you!
