### ISSUE TITLE
Attempting to retrieve bills seems to return duplicate entries 

### ISSUE THREAD

**Issue by jerusalemmoorework** [LibraryOfCongress/api.congress.gov#272]
I'm not sure if this is an error in implementation, but I am attempting to acquire all bills of a specific type for example "HR".  while processing the items 

```

VALID_STATUS_CODE = 200
def get_request_data(url):
    response = requests.get(url)
    if response.status_code != VALID_STATUS_CODE:
        raise RequestException(
            f"We received a bad response from request url: {url},"
            f" code: {response.status_code}, content: {response.text}"
        )
    return response.json()

def get_bill_data(bill_type):
    current_congress = get_curr_congress_metadata()["congress_number"]
    offset = 0 
    url = f"https://api.congress.gov/v3/bill/{current_congress}/{bill_type}?sort=updateDate+desc&api_key={APIKEY}&limit={offset}"
    bills = get_request_data(url)["bills"]
    all_bills = {}
    while bills:
        for bill in bills:
            if bill["number"] in all_bills: 
                print("ERROR")
                print(bill)
                print(all_bills[bill["number"]])
                print(bill == all_bills[bill["number"]])
                exit(1)
            all_bills[bill["number"]] = bill
        offset += 250
        url = f"https://api.congress.gov/v3/bill/{current_congress}?sort=updateDate+desc&api_key={APIKEY}&limit={offset}"
        bills = get_request_data(url)["bills"]
    return all_bills 

```

the intent of the following is to retrieve all bills of a specific type by incrementing the offset and sending new requests.  In order to check for uniqueness i am storing the bill data in a dictionary with the bill_number as value and quitting if i'm adding a bill that is already present in the dictionary. frequently it seems the data i get from url https://api.congress.gov/v3/bill/{current_congress}/{bill_type}?sort=updateDate+desc&api_key={APIKEY}&limit={offset} gives me a bill i've already received from the previous query and exits when it sees the bill already inside of my dict.

the following is output showing generated from running the above showing the bill data I received from the current request, and what's already inside the dict (data from the previous data request)

> ERROR
> {'congress': 118, 'latestAction': {'actionDate': '2024-01-22', 'text': 'Received in the Senate and Read twice and referred to the Committee on the Judiciary.'}, 'number': '4250', 'originChamber': 'House', 'originChamberCode': 'H', 'title': 'PRESS Act', 'type': 'HR', 'updateDate': '2024-09-04', 'updateDateIncludingText': '2024-09-04', 'url': 'https://api.congress.gov/v3/bill/118/hr/4250?format=json'}
> {'congress': 118, 'latestAction': {'actionDate': '2024-01-22', 'text': 'Received in the Senate and Read twice and referred to the Committee on the Judiciary.'}, 'number': '4250', 'originChamber': 'House', 'originChamberCode': 'H', 'title': 'PRESS Act', 'type': 'HR', 'updateDate': '2024-09-04', 'updateDateIncludingText': '2024-09-04', 'url': 'https://api.congress.gov/v3/bill/118/hr/4250?format=json'}
> True

Question. Shouldn't I be recieving entirely unique bills from every new request if i query by type and increment offset by 250?

**Comment by apreiter18** [comment]
@jerusalemmoorework - I hope I am understanding this correctly, please correct me if I am wrong. Limit and offset are not the same thing. The max limit is 250, and this:

url = [https://api.congress.gov/v3/bill/{current_congress}?sort=updateDate+desc&api_key={APIKEY}&limit={offset}]
 
should be this:

url = f"[https://api.congress.gov/v3/bill/{current_congress}?sort=updateDate+desc&api_key={APIKEY}&offset={offset}]

Let me know if you have any questions. Thanks!

**Comment by jerusalemmoorework** [comment]
oh my, yes that is an obvious typo on my part thank you

**Comment by jerusalemmoorework** [comment]
reopening for follow up question. i see if i query for all bills i get the
