### ISSUE TITLE
Incomplete list of congress members using /member/congress/{congress}

### ISSUE THREAD

**Issue by Kenneth-TIAN** [LibraryOfCongress/api.congress.gov#275]
When I tried to retrieve the list of congress members of the 94th session, the API only returned me ONE member. The same error occurred when I tried on Congress.gov API. 
<img width="597" alt="Screenshot 2024-09-26 at 20 39 26" src="https://github.com/user-attachments/assets/b86a74a9-673c-4cfa-b1bf-b000533ebcb5">
<img width="1457" alt="Screenshot 2024-09-26 at 20 38 36" src="https://github.com/user-attachments/assets/87f6a745-c510-466a-af9e-ce4c712c032f">

**Comment by apreiter18** [comment]
Thanks for reporting this - we are investigating.

**Comment by apreiter18** [comment]
@Kenneth-TIAN - we have a ticket to investigate this but, in the meantime, this workaround might be helpful:

https://api.congress.gov/v3/member/congress/94?currentMember=false&api_key=[INSERT_KEY]

This should return 546 members as intended.

**Comment by Kenneth-TIAN** [comment]
I worked well! Thx!

**Comment by apreiter18** [comment]
We are in the process of adding the currentMember filter to all the new member endpoints, which will return accurate data. Documentation will be updated, along with the swagger file and api.congress.gov website. The target is early October. Thanks!
