### ISSUE TITLE
Workers with Disabilities improvement 

### ISSUE THREAD

**Issue by Pinball97** [LibraryOfCongress/api.congress.gov#276]
Living with disabilities is hard , expensive, and stressful. Working in general is stressful but having a disability that has impacts your day to day life and having same expectations as an able body person is hard to achieve consistently as a disabled person. On top of most disabled individuals not qualifying to be on disability putting them in a situation where they need to have a job but may lack the consistency and energy as a person who doesn’t have a disability putting disabled people at risk at getting let go faster. Employers provide minimal support to disabled employee because they view if you disabled it’s a privilege to work opposed to we are human too and aren’t exempt from paying bills and may have more bills . Employers don’t understand limitations of disabled employees and brush off needs . For example I have high functioning autism spectrum disorder, severe ADHD , mild PTSD , POTS , and in the process of getting diagnosed with EDS . My work was aware of my disabilities I have but never took them serious as I can do most things and didn’t understand why I was so burnt out. Earlier this year got put on medical leave for autism burnout from work . I was unable to function and had no energy . About half out team was burnt out and I’m  the only disabled person and synchrony didn’t take it as an issue that able bodied team members were burnt out and didn’t realize that a disabled member of the team would be super burnt out because with disabilities it takes a larger input of energy . I was on leave for autism burnout in spring . When I came back from medical leave they increased our call metric by 50% with no sort of compensation increase while employees were already burnt out on that team . I tried really hard to get accommodations for my disability to be able to handle a 50% work increase and nothing was really done because no one had the background or able to comprehend how hard it is to work with a disability with multiple disabilities . After saying for weeks I needed help maintaining the new metric and so exhausted . Ended up having bad Vertigo episodes related to POTS , constant sensory overload related to autism from overstimulation and panic attacks and while dealing with all this I’m still working . On August 21 was so dizzy couldn’t stand so I  taken to hospital while at work . Took some scans and had a minor stroke , which I’m in my 20s nobody in there 20s should be having  a stroke while working at there desk. Employers do not provide enough support to disabled employees. Even though people with disabilities can do so much many of us still have struggles and limitations and less energy than able bodied individuals . If there was a law in place to protect disabled employees diagnosed with a disability recognized by the Americans with disabilities Act for example any forms of autism spectrum disorder that doesn’t/ hasnt qualified for disability because they have to work with an impairment there should be a job protection or compensation adjustment to help with medical treatments or an optional additional insurance they could pay into to gain PTO to go to doctors appointment and prevent stuff like severe levels of autism burnout something in place to help disabled individuals be contributing members of society but not destroying there health to pay bills

**Comment by Gmanicus** [comment]
You have my sympathy, but please reach out to your state & federal Representatives and Senators instead of communicating this here. This is for developers, researchers, and other users to communicate issues and suggestions with the Congress.gov API development team. Posting unrelated things here makes it harder for the Congress.gov team to manage and harder for us to communicate with them.
