### ISSUE TITLE
Summaries endpoint is not working as expected

### ISSUE THREAD

**Issue by tomburge** [LibraryOfCongress/api.congress.gov#278]
Here are 5 examples of using the base summaries endpoint and it is not working as expected with 3 of the 5 examples.

The base summaries endpoint along the congress and congress and bill type endpoints have the same behavior.

Example 1:

Endpoint with no filters: https://api.congress.gov/v3/summaries

Response: {'pagination': {'count': 0}, 'request': {'contentType': 'application/json', 'format': 'json'}, 'summaries': []}

Issue: No results are returned.

Example 2:

Parameters: {'limit': 5}

Endpoint with filter limit: https://api.congress.gov/v3/summaries

Response: {'pagination': {'count': 0}, 'request': {'contentType': 'application/json', 'format': 'json'}, 'summaries': []}

Issue: The limit filter is not being applied to the endpoint and no results are returned.

Example 3: 

Parameters: {'limit': 5, 'offset': 1}

Endpoint with limit and offset: https://api.congress.gov/v3/summaries

Response: {'pagination': {'count': 0, 'prev': 'https://api.congress.gov/v3/summaries?offset=0&limit=5&format=json'}, 'request': {'contentType': 'application/json', 'format': 'json'}, 'summaries': []}

Issue: There is a prev but not next and no results are returned.

Example 4:

Parameters: {'fromDateTime': '2021-01-01T00:00:00Z'}

Endpoint with fromDateTime filter: https://api.congress.gov/v3/summaries

Response: {'pagination': {'count': 89768, 'next': 'https://api.congress.gov/v3/summaries?fromDateTime=2021-01-01T00:00:00Z&offset=20&limit=20&format=json'}, 'request': {'contentType': 'application/json', 'format': 'json'}, 'summaries': [..]}

Issue: No issue here as far as I can tell except that the argument fromDateTime is required but it does not say that in the API docs and is not consistent with other APIs that have been tested.

Example 5:

Parameters: {'fromDateTime': '2021-01-01T00:00:00Z', 'limit': 5, 'offset': 1}

Endpoint with fromDateTime, limit, and offset filters: https://api.congress.gov/v3/summaries

Response: {'pagination': {'count': 89768, 'next': 'https://api.congress.gov/v3/summaries?fromDateTime=2021-01-01T00:00:00Z&offset=6&limit=5&format=json', 'prev': 'https://api.congress.gov/v3/summaries?fromDateTime=2021-01-01T00:00:00Z&offset=0&limit=5&format=json'}, 'request': {'contentType': 'application/json', 'format': 'json'}, 'summaries': [...]}

Issue: No issue. Working as expected.

**Comment by apreiter18** [comment]
@tomburge - Thank you for reporting this. I have created an investigation and fix ticket to resolve this. Please check the change log in coming weeks for any relevant updates.

**Comment by apreiter18** [comment]
@tomburge - I figured this out and have updated our documentation, along with the examples on api.congress.gov. By default, only bill summaries published in the last day are available from this endpoint unless "fromDateTime" and/or "toDateTime" parameters are added to the API request (read more about those parameters in the OpenAPI Specification, on the Summaries endpoint documentation; however, all bill summaries published for bills available on Congress.gov can be found at the [bill endpoint](https://github.com/LibraryOfCongress/api.congress.gov/blob/main/Documentation/BillEndpoint.md#summaries-level). I hope this helps!

**Comment by tomburge** [comment]
That makes sense! Thanks for the clarification!
