### ISSUE TITLE
Issue with API "daily-congressional-record"

### ISSUE THREAD

**Issue by RPguth20** [LibraryOfCongress/api.congress.gov#279]
Hi, I am trying to compile a list of all of the links to access the daily edition of the congressional record for a research paper. To this end, I am trying to use the following request:

"get(https://api.congress.gov/v3/daily-congressional-record?format=json&offset=5501&limit=5751&api_key=[my-api-key])"

Up until item 5206, this method functions perfectly but as soon as I perform this request on items 5207 and beyond, I get a null response. 

In R I get this error message:

Error in get(https://api.congress.gov/v3/daily-congressional-record?format=json&offset=5501&limit=5751&api_key=[my-api-key]) : 
  object 'https://api.congress.gov/v3/daily-congressional-record?format=json&offset=5501&limit=5751&api_key=(my-api-key)' not found

To be clear my API key is in the command I am using but I have omitted it here.

**Comment by RPguth20** [comment]
it appears that no value prior to 1995 is ever returned

**Comment by apreiter18** [comment]
@RPguth20 - yes, you are correct. The coverage dates for the Daily Congressional Record are 1995 to the present. You can read more about coverage dates [here](https://www.congress.gov/help/coverage-dates).
