### ISSUE TITLE
Question: Committee Data and Documents- Timing with Data

### ISSUE THREAD

**Issue by BrandonChiazza** [LibraryOfCongress/api.congress.gov#281]
Hello: 

Thanks for all of your previous help. I have a follow-up question. 

We looked at a comparison of both house and senate committee websites to congress.gov and found that some data was missing or came in significantly delayed with respect to documents, hearing information, etc. See attached. 

[10.18 Committee Hearings Documents QA.xlsx](https://github.com/user-attachments/files/17493377/10.18.Committee.Hearings.Documents.QA.xlsx)

I was hoping you could provide more clarity on how the data and documents are entered for senate and house committees on Congress.gov and ultimately become available via the API. Specifically, looking to answer the following: 

- How long does it typically take for Committee data to be entered in Congress.gov after a hearing occurs?
- How long does it typically take for Committee documents to be entered in Congress.gov after a hearing occurs? Are there specific Committees that take longer?
- Is there any data missing between Senate or House Committee websites and Congress.gov or will it be eventually consistent? 
- Can we rely on Congress.gov and its API as the source of truth for Committee related information such as the documents and data or do we have to go to the specific Committee websites? 

Thank you again for all of your support in advance. I appreciate any clarification you can provide with these questions.

**Comment by apreiter18** [comment]
@BrandonChiazza - I wanted to check if you had any follow up questions here? Thanks much!

**Comment by BrandonChiazza** [comment]
This is great. thank you
