### ISSUE TITLE
I cannot find a privacy policy for the usage of this API.

### ISSUE THREAD

**Issue by paul-rinaldi** [LibraryOfCongress/api.congress.gov#282]
I've searched the docs and the github and cannot find a policy for the privacy of clients using this API. Sorry if I missed it but I believe this is something that should be easy to find and obvious to the developers using this API.

**Comment by paul-rinaldi** [comment]
I did find this policy: https://www.gsa.gov/website-information/website-policies#privacy

**Comment by apreiter18** [comment]
There are two pertinent privacy policies for the Congress.gov API:

1. API keys and user registration follow the [data.gov private policy](https://data.gov/privacy-policy/).
2. API content follows the [Library of Congress privacy policy](https://www.loc.gov/legal/privacy-policy/).

Hope this helps - happy reading, @paul-rinaldi!

**Comment by apreiter18** [comment]
One more thing - I added the links to these policies [here](https://github.com/LibraryOfCongress/api.congress.gov/blob/main/README.md).
