### ISSUE TITLE
403 Client Error: Forbidden for url

### ISSUE THREAD

**Issue by sharmilee-sivakumaran** [LibraryOfCongress/api.congress.gov#284]
Getting this HttpException when trying to access https://crsreports.congress.gov:
403 Client Error: Forbidden for url: https://crsreports.congress.gov/Search/GetCsvForFixedNumberSearchResults/

Also, I am unable to find a contact information for the webmaster or IT services for the website. 
Is this the right forum to post the issue? 

Any help would be greatly appreciated !

**Comment by apreiter18** [comment]
HI @sharmilee-sivakumaran - this is a Git space specifically for the Congress.gov API. I would recommend contacting the Law Library of Congress, more information [here](https://www.congress.gov/contact-us) under the "Ask a Law Librarian" section. They will be able to direct your inquiry accordingly. Thanks.
