### ISSUE TITLE
Lots of new bills not returning a text object?

### ISSUE THREAD

**Issue by csparksnj** [LibraryOfCongress/api.congress.gov#289]
Im downloading new bill information daily, and a lot of them come back without any text version. Some examples are.

https://api.congress.gov/v3/bill/118/s/5321/text?api_key=123
https://api.congress.gov/v3/bill/118/s/5315/text?api_key=123
https://api.congress.gov/v3/bill/118/s/5317/text?api_key=123

It seems like this issue is mostly for bills coming out of the Senate. Is there anything I can do to get the full text versions of newly introduced bills?

It returns a blob like this

```
{
    "pagination": {
        "count": 0
    },
    "request": {
        "billNumber": "5317",
        "billType": "s",
        "billUrl": "https://api.congress.gov/v3/bill/118/s/5317?format=json",
        "congress": "118",
        "contentType": "application/json",
        "format": "json"
    },
    "textVersions": []
}
```

**Comment by chrissparksnj** [comment]
Thank you.
