### ISSUE TITLE
Subcommittee Name Typo

### ISSUE THREAD

**Issue by dholle02** [LibraryOfCongress/api.congress.gov#294]
In the /committee/{Congress}/house endpoint, hsed13's name is is being reported as "Higher Education and Workforce Development Subcomittee" - subcommittee is misspelled.
![Subcom Typo](https://github.com/user-attachments/assets/dc016c9f-e6bf-4e56-aa90-acd4d75ce7bb)

**Comment by apreiter18** [comment]
Thank you, @dholle02 - this has been corrected. Can you confirm if all looks good on your end, as well?
