### ISSUE TITLE
swagger specification is incorrect in repo (though is fine online)

### ISSUE THREAD

**Issue by jcocozza** [LibraryOfCongress/api.congress.gov#298]
When making requests to `api.congress.gov`, the api key is expected in the url as a parameter with the key `api_key`
This is correctly noted in the online documentation, for example `https://api.congress.gov/v3/bill?api_key=[INSERT_KEY]`.

However, both the [swagger.json](https://github.com/LibraryOfCongress/api.congress.gov/blob/main/Documentation/swagger.json) and [swagger.yaml](https://github.com/LibraryOfCongress/api.congress.gov/blob/main/Documentation/swagger.yaml) are written so that the url parameter will be: `@auth_key`. Which is to say, it will try to make the above request like: `https://api.congress.gov/v3/bill?@auth_key=[INSERT_KEY]`.

The issue is in the `securityDefinitions`:
```
"securityDefinitions": {
        "api_key": {
            "type": "apiKey",
            "name": "@auth_key",
            "in": "query"
        }
    }
```

The fix is also easy, simply change the above `name` key to have value `api_key`:
```
"securityDefinitions": {
        "api_key": {
            "type": "apiKey",
            "name": "api_key",
            "in": "query"
        }
    }
```

A very similar process should be done for the yaml file as well.

**Comment by apreiter18** [comment]
Thanks for reporting this, @jcocozza - we have updated both the swagger.json and swagger.yaml files.
