### ISSUE TITLE
CORS error

### ISSUE THREAD

**Issue by lukefretwell** [LibraryOfCongress/api.congress.gov#33]
The cross origin resource sharing is disabled for the server, so the API can't be accessed from another domain.

Code:
```javascript
const req = new XMLHttpRequest();
req.open('GET', 'https://api.congress.gov/v3/member?format=json&api_key=<KEY>');
req.onload = function () { console.log(JSON.parse(this.response)) };
req.send();
```
Result:
```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at 
https://api.congress.gov/v3/member?format=json&api_key=<KEY>. 
(Reason: CORS header ‘Access-Control-Allow-Origin’ missing).
```

[Reference](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSMissingAllowOrigin)

**Comment by mnewatloc** [comment]
Thank you for bringing this to our attention. We will investigate.

**Comment by lukefretwell** [comment]
Any updates or ETA?

**Comment by rbram** [comment]
Thanks for your feedback. We are still investigating this and don’t yet have an update.

**Comment by lukefretwell** [comment]
Thank you. Seems like this API isn't really an API then, right?

**Comment by mnewatloc** [comment]
Please re-test and let us know if you’re still seeing errors.

**Comment by lukefretwell** [comment]
Yes, it's working now. Thank you!
