### ISSUE TITLE
Rate Limit

### ISSUE THREAD

**Issue by jackwilmerding** [LibraryOfCongress/api.congress.gov#35]
Hi, big fan of this API, high time Congress.gov got one.

I was wondering what the actual rate limit on requests is. My script hit it, and I need to know how to time its requests so that it doesn't happen and I don't put unreasonable strain on your servers. I can't seem to find it in any documentation. Thanks!

Also, are there any plans to add the sponsor's bioguideID to a bill result?

**Comment by gautiermorel** [comment]
@mnewatloc Hi, I guess you moved "Possible future development" for the latest question of @jackwilmerding, but to do we have more information about rate limits ? I am also unable to find any information about it...
Thank you :)

**Comment by mnewatloc** [comment]
The rate limit is set high enough to allow most well-behaved robot programs to call it. From time to time, our Operations team adjusts the rate limits based on operational needs so we cannot provide a specific number. 

Regarding your question about adding BioguideID, it's present at the bill item like at https://api.congress.gov/v3/bill/117/hr/1?api_key=

**Comment by jackwilmerding** [comment]
You can’t “extend the limit” any other way than waiting for your calls per minute to reset. The limit exists for a reason, if we all “extended” it, none of us could use the API due to overload :) If you get this error code, have your script catch it, wait 10 minutes, and resume trying. I’d also wait a second between each call.
