### ISSUE TITLE
Undefined example after creating an API key

### ISSUE THREAD

**Issue by joshrotenberg** [LibraryOfCongress/api.congress.gov#36]
I created an API key a little while ago, and on the confirmation page I see the following under my new key:

<img width="822" alt="Screen Shot 2022-09-13 at 11 32 21 AM" src="https://user-images.githubusercontent.com/3231/190003168-a97d8a59-4d98-46d5-aa8d-dc737c1997a9.png">

This links to <https://api.congress.gov/sign-up/undefined>, which just gives me this:

<img width="520" alt="Screen Shot 2022-09-13 at 1 31 21 PM" src="https://user-images.githubusercontent.com/3231/190003486-56f2b55e-d272-4a92-a85a-5a10fdd6f745.png">

**Comment by joshrotenberg** [comment]
As a side note, the `contact us` link on that page points to <https://www.congress.gov/contact-us> which doesn't seem to have anything specific to contacting support specific to the API. There is a link to this repo, which is definitely more helpful, but if there is another support channel it might be more helpful to link directly to that. My guess is that my member of congress generally won't be particularly helpful with API questions.

**Comment by mnewatloc** [comment]
This issue is already in our near-term backlog and will be addressed soon. Watch the [changelog](https://github.com/LibraryOfCongress/api.congress.gov/blob/main/ChangeLog.md) for updates.

**Comment by sfbaker7** [comment]
+1, when I pass in api_key or apiKey as a query param I get a 443. I think openapi has a way to add API keys to the security spec so that examples are autogenerated in the docs [Link](https://swagger.io/docs/specification/authentication/api-keys/)

**Comment by heDevs** [comment]
I've been playing with the Python example after seeing this issue I was having myself. In the python example, there is an x-api-key header set like so (as a curl header example):

curl https://api.congress.gov/v3/bill -H "x-api-key: your_api_key"

I tried this in my terminal and it worked. Hope that helps

**Comment by rbram** [comment]
Thanks for reporting this. The undefined example has been replaced by a bill request.
