### ISSUE TITLE
Pagination URLS don't work with the api key

### ISSUE THREAD

**Issue by PatrickBriggs** [LibraryOfCongress/api.congress.gov#37]
# Issue

Pagination urls do not work with the api key that was used to access the resource.

Accessed endpoint: https://api.congress.gov/v3/bill/117/hr/4521/actions?format=json

Pagination urls response: 

https://api.data.gov/congress/v3/bill/117/hr/4521/actions?offset=20&limit=20&format=json

this url doesnt work but if we move congress to replace data like so: 

https://api.congress.gov/v3/bill/117/hr/4521/actions?offset=20&limit=20&format=json

it works.

[example.json.zip](https://github.com/LibraryOfCongress/api.congress.gov/files/9571890/example.json.zip)

**Comment by moonshiner** [comment]
This may be a duplicate of https://github.com/LibraryOfCongress/api.congress.gov/issues/26

**Comment by PatrickBriggs** [comment]
This is indeed a duplicate.
