### ISSUE TITLE
Special Election Handling

### ISSUE THREAD

**Issue by jackwilmerding** [LibraryOfCongress/api.congress.gov#38]
When I get all bills from a congress (the 115th at least), special election appointees like Mary Gay Scanlon aren't present in any sponsorships or cosponsorships despite being present on the website. I don't know if this is an issue confined to the 115th or not.

**Comment by mnewatloc** [comment]
We're looking into this.

**Comment by jackwilmerding** [comment]
Hi Mike,

Unconfirmed thus far, but I think I may have traced the problem to a pagination issue with bill/cosponsors endpoints. There was no mention of a need to do offsetting or limit setting in the documentation, so I was only ever getting the first 20 cosponsors of a bill and missing some members as a result. This of course missed people who might have cosponsored later than others (like special electees).

A fix would be editing the api.congress.gov site to include these arguments as necessary to that endpoint.

I really appreciate your whole team's work on this project. When I was on the Hill, LOC was always the most helpful and enthusiastic group there.
