### ISSUE TITLE
Metadata Endpoint

### ISSUE THREAD

**Issue by AMGold99** [LibraryOfCongress/api.congress.gov#39]
Is there an endpoint/url that users can call to retrieve all currently available endpoints (bills, amendments, etc.) and additional options for each endpoint (e.g., "sort," "fromDateTime," etc.)?

**Comment by mnewatloc** [comment]
If you visit https://api.congress.gov/, you can view available endpoints and parameters. Please note that there will be updates to this page to account for the Senate Communications API, as well as other parameters available for endpoints.

**Comment by miriamasagold** [comment]
Are you planning on providing an endpoint akin to the Census's https://api.census.gov/data.json where users can programmatically retrieve metadata as a structured list/dataframe, etc.?

**Comment by moonshiner** [comment]
I love this data.json idea as I've used similar elsewhere.

**Comment by mnewatloc** [comment]
Thanks for the feedback. We'll explore this as a possible future feature.
