### ISSUE TITLE
urls returned from /treaty start with "http://https://"

### ISSUE THREAD

**Issue by cheezedoodle2** [LibraryOfCongress/api.congress.gov#41]
The `url` attribute in the `treaties` array returned from the `/treaty` endpoint seems to be malformed:

```
curl -s https://api.congress.gov/v3/treaty/ | jq '.treaties[].url'
"http://https://api.data.gov/congress/v3/treaty/117/1?format=json"
"http://https://api.data.gov/congress/v3/treaty/112/8?format=json"
"http://https://api.data.gov/congress/v3/treaty/116/2?format=json"
"http://https://api.data.gov/congress/v3/treaty/117/3?format=json"
"http://https://api.data.gov/congress/v3/treaty/115/3?format=json"
"http://https://api.data.gov/congress/v3/treaty/117/7?format=json"
"http://https://api.data.gov/congress/v3/treaty/117/2?format=json"
```

**Comment by mnewatloc** [comment]
This should be fixed in the next release. Check the [Changelog](https://github.com/LibraryOfCongress/api.congress.gov/blob/main/ChangeLog.md) for updates.

**Comment by rbram** [comment]
Thanks for your feedback. I just wanted to let you know that our developers are working to address this issue in a near-term release.

**Comment by rbram** [comment]
Hello. We have addressed this issue. Please let us know if you have any more problems with it.
