### ISSUE TITLE
CORS Preflight Request - denied access

### ISSUE THREAD

**Issue by 0xAskar** [LibraryOfCongress/api.congress.gov#44]
I'm getting the following error 
```Access to fetch at 'https://api.congress.gov/v3/bill?api_key=<apikey>' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.```

Here's my code: 
```
let url = "https://api.congress.gov/v3/bill?api_key=" + process.env.NEXT_PUBLIC_CONGRESS_KEY
    console.log(url)
    const options = {
        method: "GET",
        headers: {
            "Content-Type": "application/xml",
        },
        mode: "cors"
    }
    let response = await fetch(url, options)
 ```
 Any idea why?
Would this be a [possible solution?](https://stackoverflow.com/questions/44736327/node-js-cors-issue-response-to-preflight-request-doesnt-pass-access-control-c)

**Comment by mnewatloc** [comment]
This seems to be the same as issue[33](https://github.com/LibraryOfCongress/api.congress.gov/issues/33)

**Comment by mnewatloc** [comment]
We’ve made some changes to the code. Please re-test and let us know if you’re still seeing errors.
