### ISSUE TITLE
Actions Overview

### ISSUE THREAD

**Issue by spoonstein** [LibraryOfCongress/api.congress.gov#45]
Ref. https://www.congress.gov/bill/117th-congress/house-bill/7108/actions?q=%7B%22search%22%3A%22Trade+Relations%22%7D&r=1&s=3

When reviewing a bill (ref above) that's been made into law, I see the actions overview for the bill which almost match 1:1 with the tracker above. Is there a recommended way to pull this kind of information using the API? I may be missing something obvious and would appreciate any pointers. My goal is to pull the dates for major actions that effectively map with the tracker or something close to it. Thanks!

**Comment by mnewatloc** [comment]
We recommend that you retrieve actions (and related data) like those shown in the overview on Congress.gov by using the actionCode element where the sourceSystem value is 9 (for Library of Congress). For example, actionCode = 36000 is used for “Became Public Law”. An authoritative list of Library of Congress action codes can be found at https://www.congress.gov/help/field-values/action-codes. You can read more about action codes in the [bill endpoint documentation](https://github.com/LibraryOfCongress/api.congress.gov/blob/main/Documentation/BillEndpoint.md#actions-level).

**Comment by spoonstein** [comment]
Awesome. Thanks!
