### ISSUE TITLE
How to get full bill texts in .txt format? 

### ISSUE THREAD

**Issue by humancoder** [LibraryOfCongress/api.congress.gov#49]
I am not seeing a full text endpoint for bills. Is this available? If not, what is my second best option?

**Comment by rbram** [comment]
Hello. Thanks for your question. It is referred to under textVersions on the bill endpoint. 
e.g. https://api.congress.gov/v3/bill/117/hr/1?api_key=DEMO_KEY 
returns 
<textVersions>
<count> 3 </count>
<url> https://api.congress.gov/v3/bill/117/hr/1/text?format=xml </url>
and the API 
https://api.congress.gov/v3/bill/117/hr/1/text?api_key=DEMO_KEY
returns all the text versions.

**Comment by rbram** [comment]
Thanks for your questions. It is referred to under textVersions on the bill endpoint. 
e.g. https://api.congress.gov/v3/bill/117/hr/1?api_key=DEMO_KEY 
returns 
<textVersions>
<count> 3 </count>
<url> https://api.congress.gov/v3/bill/117/hr/1/text?format=xml </url>
and the API 
https://api.congress.gov/v3/bill/117/hr/1/text?api_key=DEMO_KEY
returns all the text versions. 
`

**Comment by humancoder** [comment]
Thanks.. I have used this method to some success actually, but I was wondering if there were dedicated api endpoints?  I'm wondering for three reasons: 1. I was having request limits when using this method. My responses started to include, "[www.congress.gov](http://www.congress.gov/) needs to review the security of your connection before proceeding" when I made requests were for more than a few hundred at once. (I'm trying to get over 90k texts of bills.) 2. I'm thinking dedicated api endpoints could potentially be faster. 3. I'm hoping to just receive .txt files instead of formatted files. I think I can pretty easily strip the markdown for the .htm files though...?
Sorry, I should've been more specific in my original comment.

**Comment by rbram** [comment]
Thanks for your feedback. We will look into doing this in the future, but we are prioritizing bugs and other current offerings at the moment. We don't have bill text files with a .txt file extension, but as you say, you can strip the markdown from the .htm files.

**Comment by humancoder** [comment]
Ok thanks for confirming that there aren't .txt files available. Cheers

**Comment by humancoder** [comment]
Also, can I provide you with my IP address so that I can be whitelisted to make the .htm calls directly to the website? I was being blocked by the server because of security concerns.

**Comment by rbram** [comment]
Thanks for your question. Could you please reduce the amount of calls so as not to be marked as a either a robot or a DDOS attack by our Cloud security provider?

**Comment by humancoder** [comment]
I am trying my best to be resourceful, but I can't find a bulk downloader or API with full bill texts that isn't extremely limited. Most only allow downloads of full text starting from the 113th congress. I would like to get full bill texts starting back at 107th congress. Right now, I am trying to make a bit over 90k call for full texts, but it seems that when I even try to call a few hundred or few thousand at time, my calls are being stopped by the API.

**Comment by mathhulk** [comment]
> I am trying my best to be resourceful, but I can't find a bulk downloader or API with full bill texts that isn't extremely limited. Most only allow downloads of full text starting from the 113th congress. I would like to get full bill texts starting back at 107th congress. Right now, I am trying to make a bit over 90k call for full texts, but it seems that when I even try to call a few hundred or few thousand at time, my calls are being stopped by the API.

Unfortunately, public APIs need to be rate limited to give everyone equal access. They can be both resource-intensive and use excessive amounts of bandwidth. I would suggest working around this issue by making X amount of API calls per day or only querying for data when necessary.

**Comment by jackwilmerding** [comment]
Agreeing with @mathhulk, my implementation using this system did bulk downloading but did so slowly over the course of about two weeks. @humancoder it's unfortunate that LOC's resources aren't infinite, but expecting them to change the architecture to suit extreme needs is unrealistic. Take it slow, store the data piecemeal as you go, catch the 429 errors, and have your script wait a little bit after each rate limit to give the servers a break. Given time, it'll all work out! It did for us.

Here's a sample of what your script might look like in pseudocode:

`
for each congress:
    for each bill in that congress:
        request bill
        if request code == 429 (too many requests):
            wait 10 minutes
            request bill again, if still not there, wait another 10, repeat until the error code clears
`

**Comment by bpri** [comment]
If you are looking for Bulk Download of bill text then GPO's Govinfo.gov site may be a more appropriate option for you:
https://www.govinfo.gov/bulkdata/BILLS

**Comment by jonquandt** [comment]
how does this sound?



-----------



Hi - note that the GovInfo Bulk Data repository contains bulk XML from the 113th Congress forward..



You may also be interested in the GovInfo API, where you can also access BILLS back to 1994. GovInfo is the source for the BILLS content on congress.gov.



**Collections Request for all available BILLS:** https://api.govinfo.gov/collections/BILLS/2021-01-01T00:00:00Z?offsetMark=*&pageSize=1000&api_key=DEMO_KEY
**Package Summary:** https://api.govinfo.gov/packages/BILLS-117s5064is/summary?api_key=DEMO_KEY
**Bill Text:** https://api.govinfo.gov/packages/BILLS-117s5064is/htm?api_key=DEMO_KEY

You could grab a list of all BILLS from the collections endpoint, and then execute individual requests for the text by appending {{packageId}}/htm to the packages endpoint. 

Generally, the BILLS text are plain text files encoded in <pre> tags with an .htm extension.

**Comment by humancoder** [comment]
> If you are looking for Bulk Download of bill text then GPO's Govinfo.gov site may be a more appropriate option for you: https://www.govinfo.gov/bulkdata/BILLS

As  @jonquandt says they only start at 113th Congress, I want data that goes further back.

**Comment by humancoder** [comment]
> Hi - note that the GovInfo Bulk Data repository contains bulk XML from the 113th Congress forward..
> 
> You may also be interested in the GovInfo API, where you can also access BILLS back to 1994. GovInfo is the source for the BILLS content on congress.gov.
> 
> **Collections Request for all available BILLS:** https://api.govinfo.gov/collections/BILLS/2021-01-01T00:00:00Z?offsetMark=*&pageSize=1000&api_key=DEMO_KEY **Package Summary:** https://api.govinfo.gov/packages/BILLS-117s5064is/summary?api_key=DEMO_KEY **Bill Text:** https://api.govinfo.gov/packages/BILLS-117s5064is/htm?api_key=DEMO_KEY
> 
> You could grab a list of all BILLS from the collections endpoint, and then execute individual requests for the text by appending {{packageId}}/htm to the packages endpoint.
> 
> Generally, the BILLS text are plain text files encoded in `\<pre\>` tags with an .htm extension.

Thanks @jonquandt! It makes sense to ping an api and not a website.

**Comment by humancoder** [comment]
> Agreeing with @mathhulk, my implementation using this system did bulk downloading but did so slowly over the course of about two weeks. @humancoder it's unfortunate that LOC's resources aren't infinite, but expecting them to change the architecture to suit extreme needs is unrealistic. Take it slow, store the data piecemeal as you go, catch the 429 errors, and have your script wait a little bit after each rate limit to give the servers a break. Given time, it'll all work out! It did for us.
> 
> Here's a sample of what your script might look like in pseudocode:
> 
> ```
> for each congress:
>     for each bill in that congress:
>         request bill
>         if request code == 429 (too many requests):
>             wait 10 minutes
>             request bill again, if still not there, wait another 10, repeat until the error code clears
> ```

This makes sense. Were you calling for you the full bill texts? Since it doesn't have an actual api endpoint, the behavior seems to be a bit unusual.

**Comment by humancoder** [comment]
> > I am trying my best to be resourceful, but I can't find a bulk downloader or API with full bill texts that isn't extremely limited. Most only allow downloads of full text starting from the 113th congress. I would like to get full bill texts starting back at 107th congress. Right now, I am trying to make a bit over 90k call for full texts, but it seems that when I even try to call a few hundred or few thousand at time, my calls are being stopped by the API.
> 
> Unfortunately, public APIs need to be rate limited to give everyone equal access. They can be both resource-intensive and use excessive amounts of bandwidth. I would suggest working around this issue by making X amount of API calls per day or only querying for data when necessary.

Someone at the library of congress told me I could get whitelisted so I was just pursuing that. There isn't an API endpoint for bill texts so the limits and calls get ruined at unknown and low rates. I think the daily limit for api calls is 5k or more to this api but I couldn't make more than 100 at once without getting blocked. I realize getting whitelisted probably isn't going to happen so I'll try govinfo first and then try this with wait statements.

**Comment by mnewatloc** [comment]
We have increased the rate limit. Please let us know if that's helpful.

**Comment by humancoder** [comment]
> We have increased the rate limit. Please let us know if that's helpful.

Thanks!.. I'm trying the govinfo.gov api now b/c its has dedicated endpoints, but it does seems a bit slower than just calling the website urls for text.

**Comment by BhinbahadurUK** [comment]
Direct reform
Tacacs regeneration to auto find
Payments to find dos entry first
Human anoid for payments to find you. Will work on the magic segment

UK Bhinbahadur
