### ISSUE TITLE
Sponsored legislation API URL not correct?

### ISSUE THREAD

**Issue by lukefretwell** [LibraryOfCongress/api.congress.gov#50]
`sponsoredLegislation.url` and `cosponsoredLegislation.url` on `/member/{bioguideId}` gives a URL starting with `https://api.data.gov/congress/`, which doesn't work. 

Reference:

[Member](https://api.congress.gov/v3/member/B001261)
[Non-working URL](https://api.data.gov/congress/v3/member/B001261/sponsored-legislation)

Suggestion: Change URL or fix the current one.

**Comment by rbram** [comment]
Hello. The URLs have been corrected. Please test again.
