### ISSUE TITLE
API Key giving 403

### ISSUE THREAD

**Issue by mrf52** [LibraryOfCongress/api.congress.gov#54]
Hi - I am trying to use an api key I just received and continue to get a 403 error on my request. This is my request - can someone please advise.

import requests 

api_key = {'x-api-key': 'XXXXXXXX'}
members = requests.get('https://www.congress.gov/v3/member.json', headers=api_key)

**Comment by mnewatloc** [comment]
It's probably that you're using `www.congress.gov` instead of `api.congress.gov` . Try making that change, and let us know if you have further questions.

**Comment by mrf52** [comment]
Fixed it - thanks very much!
