### ISSUE TITLE
(bill committees API):  not returning `pagination`

### ISSUE THREAD

**Issue by ryparker** [LibraryOfCongress/api.congress.gov#56]
The [`/bill/{congress}/{billType}/{billNumber}/committees` API](https://api.congress.gov/#/bill/bill_committees) does not return the `pagination` object.

Even if it is unlikely for a bill to have many committees associated, I still expected the response to be consist with other list APIs.

**Comment by mnewatloc** [comment]
We'll consider that feature for possible future development. Thanks for your input.

**Comment by apreiter18** [comment]
Hi @ryparker - this has been added https://api.congress.gov/#/bill/bill_committees endpoint. 

Here is an example: https://api.congress.gov/v3/bill/117/hr/5430/committees?api_key=[INSERT_KEY]

**Comment by ryparker** [comment]
Thanks
