### ISSUE TITLE
Do you provide a bulk download of the databases backing the API

### ISSUE THREAD

**Issue by iita-atii** [LibraryOfCongress/api.congress.gov#58]
Thank you for making this well-thought-out API! 

In order to avoid rate limits / slamming your servers it will be helpful to store data locally as well. Is there currently a way to get all or parts of the data backing the API without crawling the API?

I am aware of the bulk downloads available through govInfo but hoping to get the data standardized as it comes from the API.

**Comment by ryparker** [comment]
This would be excellent. It took about 10 days for me to crawl the /bills/* API for the 117th Congress.

**Comment by aweiss27** [comment]
Hi @iita-atii and @ryparker - 

As you noted, @iita-atii, GPO provides [bulk data for bill status information](https://www.govinfo.gov/bulkdata/BILLSTATUS) (including titles, actions, sponsor and cosponsors, and other associated metadata). That bulk data is sourced from an earlier version of the Congress.gov API. Around 12/20/22, GPO plans to start reprocessing its existing bill status collections - starting with the 117th Congress - based on the data structure of the public Congress.gov API. Around the new year, GPO should be finished reprocessing all available congresses (108th-117th). Along with the bill status data, GPO maintains a [GitHub repository](https://github.com/usgpo/bill-status) for this collection; there, you can find documentation on the data sets, a user guide, and more. @jonquandt from GPO can give you more information on the bulk data available from GPO, if you need. Thanks.

**Comment by jonquandt** [comment]
Thanks @aweiss27  -- for more information on what that will look like, please see https://github.com/usgpo/bill-status/issues/200, which includes links to sample versions of the v3-based BILLSTATUS data.

Note that our BILLSTATUS xml aggregates the individual subsidiary calls into a single xml file for easier consumption. That's a little different than @ryparker's storage approach listed above, but may still be useful to you.

**Comment by iita-atii** [comment]
This is wonderful news, thank you both for your work on this!
