### ISSUE TITLE
Unexpected empty object in early congresses' sessions array, /congress endpoint

### ISSUE THREAD

**Issue by nickzeppos** [LibraryOfCongress/api.congress.gov#59]
From 1st to 42nd congress, `/congress` endpoint returns a sessions array that contains, among expected objects, an empty object. It's not clear to me what this empty object could signify, and it's existence doesn't seem to be noted in the `/congress` endpoint [docs](https://github.com/LibraryOfCongress/api.congress.gov/blob/main/Documentation/CongressEndpoint.md).

This is the case for responses in both `'json'` and `'xml'` format, where the empty object appears as `{}` and `<item/>`, respectively.

Also appears as though this only occurs when calling the `/congress` endpoint, and not `/congress/{congress}` (i.e., `/congress/42` response contains sessions array without unexpected empty object}.

Can be seen in interactive API docs, but behavior isn't limited to interactive docs or requests made with `api_key=DEMO_KEY`. 

Truncated json example response below.
```bash
curl -X GET "https://api.congress.gov/v3/congress?format=json&limit=250&api_key=DEMO_KEY" -H "accept: application/xml"
```
```
{ "congresses":
    [
    ...
       {
            "endYear": "1873",
            "name": "42nd Congress",
            "sessions": [
            ...
                {
                    "chamber": "Senate",
                    "endDate": "1873-03-03",
                    "number": 3,
                    "startDate": "1872-12-02",
                    "type": "R"
                },
                {}
            ],
            "startYear": "1871"
        },
        ...
     ]
}     
            
```

**Comment by mnewatloc** [comment]
Thanks for your feedback. We have work scheduled in the coming months to suppress those empty objects.

**Comment by nickzeppos** [comment]
Awesome, thanks. Closing this then.
