### ISSUE TITLE
feat(member list API): sort members by updateDate

### ISSUE THREAD

**Issue by ryparker** [LibraryOfCongress/api.congress.gov#61]
## Problem

I would like to refetch member data only when changed. Currently users need to crawl the API on a schedule to be certain they have the latest member data.

## Solution

Add `updateDate` to the member list response and add the ability to sort by `updateDate`.

For example when Kyrsten Sinema changed to an independent I would expect this change to be reflected in the `updateDate` and ordered to the top of the member list API.

**Comment by rbram** [comment]
Thanks for your feedback. We will look into this. Regarding the party change, we are waiting for the official data source to update to make this change.

**Comment by mnewatloc** [comment]
We received the update for Sen. Sinema's party change and see that the record is now at the top of the list. We are working on adding update dates for that type of information at the list level.

**Comment by ryparker** [comment]
Thanks Mike

**Comment by ryparker** [comment]
Fixed. Someone can open a new issue if they're interested in the sort by updateDate functionality.
