### ISSUE TITLE
CRS Bill Summary for HR 7776 - Exact text is duplicated three times

### ISSUE THREAD

**Issue by jhanna71** [LibraryOfCongress/api.congress.gov#63]
ny idea why the CRS Bill Summary for HR 7776 has the exact text duplicated three times?

https://www.govinfo.gov/bulkdata/BILLSTATUS/117/hr/BILLSTATUS-117hr7776.xml

00 2022-05-16 Introduced in House 2022-06-08T11:45:07Z Water Resources Development Act of 2022
This bill authorizes the U.S. Army Corps of Engineers to carry out activities concerning water resources development projects, water supply and wastewater infrastructure, flood control, navigation, or ecosystem restoration, such as shoreline restoration. In addition, it modifies the process used to deauthorize certain inactive water resources development projects.

]]>
07 2022-06-07 Reported to House 2022-06-13T12:16:53Z Water Resources Development Act of 2022
This bill authorizes the U.S. Army Corps of Engineers to carry out activities concerning water resources development projects, water supply and wastewater infrastructure, flood control, navigation, or ecosystem restoration, such as shoreline restoration. In addition, it modifies the process used to deauthorize certain inactive water resources development projects.

]]>
53 2022-06-08 Passed House 2022-06-15T13:33:02Z Water Resources Development Act of 2022
This bill authorizes the U.S. Army Corps of Engineers to carry out activities concerning water resources development projects, water supply and wastewater infrastructure, flood control, navigation, or ecosystem restoration, such as shoreline restoration. In addition, it modifies the process used to deauthorize certain inactive water resources development projects.

]]>
55 2022-07-28 Passed Senate 2022-11-02T17:31:18Z Water Resources Development Act of 2022
This bill authorizes the U.S. Army Corps of Engineers to carry out activities concerning water resources development projects, water supply and wastewater infrastructure, flood control, navigation, hydropower, or ecosystem restoration, such as shoreline restoration. In addition, it modifies the process used to deauthorize certain inactive water resources development projects.

]]>

**Comment by mnewatloc** [comment]
Those summaries do appear to be identical, but they are for different versions of the bill. That's a little more clear on Congress.gov: https://www.congress.gov/bill/117th-congress/house-bill/7776
