### ISSUE TITLE
Committee alert is missing name of bill

### ISSUE THREAD

**Issue by stdoherty** [LibraryOfCongress/api.congress.gov#69]
**Today, the email alert I received from congressional committees was missing the name of the bill, please fix this function:

[Email dated 2023-01-11]**
There has been new activity by the House Transportation and Infrastructure Committee. The result set has a new total of 22,151 (4 new).

Created: 12/15/2021

Results with Changes:

Legislation

1.	H.R.250
Actions: 01/10/2023: Referred to the House Committee on Transportation and Infrastructure.
Actions: 01/10/2023: Introduced in House
Committees: House Transportation and Infrastructure
2.	H.R.255
Actions: 01/10/2023: Referred to the House Committee on Transportation and Infrastructure.
Actions: 01/10/2023: Introduced in House
Committees: House Transportation and Infrastructure
3.	H.R.259
Actions: 01/10/2023: Referred to the Committee on Transportation and Infrastructure, and in addition to the Committees on Small Business, and Financial Services, for a period to be subsequently determined by the Speaker, in each case for consideration of such provisions as fall within the jurisdiction of the committee concerned.
Actions: 01/10/2023: Introduced in House
Committees: House Financial Services; House Small Business; House Transportation and Infrastructure
4.	H.R.267
Actions: 01/10/2023: Referred to the House Committee on Transportation and Infrastructure.
Actions: 01/10/2023: Introduced in House
Committees: House Transportation and Infrastructure

**[Email dated 2023-01-10]**
Legislation

1.	H.R.103 - To prohibit the Secretary of Transportation, acting through the Administrator of the Federal Aviation Administration, from setting a requirement that air carriers and foreign air carriers must require an individual to test negative for COVID-19 to travel in air transportation on an air carrier, and for other purposes.
2.	H.R.121 - To amend the National Emergencies Act to provide that a national emergency declared by the President terminates 30 days after the declaration unless a joint resolution affirming such declaration is enacted into law, and for other purposes.
3.	H.R.125 - To prohibit the imposition of mask mandates on public transportation.
4.	H.R.132 - To amend the Robert T. Stafford Disaster Relief and Emergency Assistance Act to include algal blooms in the definition of a major disaster, and for other purposes.
5.	H.R.220 - To establish the Office of Advanced Aviation within the Administration of the Federal Aviation Administration, and for other purposes.
6.	H.J.Res.7 - Relating to a national emergency declared by the President on March 13, 2020.

**Comment by mnewatloc** [comment]
We had some data issues yesterday and several bills were missing titles. That has now been corrected.

In the future, you'll get a better and quicker response by submitting Congress.gov feedback through the Site Feedback link on the Congress.gov website. This GitHub project is meant to be used for issues related to the Congress.gov API.

**Comment by stdoherty** [comment]
https://www.congress.gov/
https://www.congress.gov/survey
https://www.congress.gov/contact-us
FYI, I did start at the Congress.gov website; the "Site Feedback" link only
had a survey or "give your opinion to Congress".  The only thing relevant
on the "Help" link was for API help.  I didn't know that was different than
"alert" problems.

Thanks,
Sharon
