### ISSUE TITLE
GETting a Vote record for legislatures

### ISSUE THREAD

**Issue by BlankDev117** [LibraryOfCongress/api.congress.gov#70]
Feature Request/Endpoint Enhancement
-----
This may be similar to https://github.com/LibraryOfCongress/api.congress.gov/issues/64, so please forgive potential redundancy.

It would be beneficial to be able to get a list o the voter record of a given individual legislature. i.e. a representative or senator's entire history of voting (yes/no/no vote) on bills across their entire tenure over all congresses they participated in.

I am able to somewhat get this data now, but it requires multiple different calls to achieve the desired result and may be worth to other users of the api.

**Comment by mnewatloc** [comment]
Yes, this looks like the same issue as #64
