### ISSUE TITLE
Inconsistent Api Structure

### ISSUE THREAD

**Issue by BlankDev117** [LibraryOfCongress/api.congress.gov#71]
Bug
-----
There are api responses from GETs and GET lists calls that have completely different responses. I understand that in an api you might provide a summary endpoint for the list that doesn't provide all the data that a singular GET would provide, but there should still be consistency between the data models.

For example when comparing the GET and GET List for members, we have different models:
A.
![image](https://user-images.githubusercontent.com/7662822/213100840-efb20ac2-febf-49dc-916b-91e19505b6b8.png)

In the above, notice on the GET list that members are only shown to have a singular bioguidId, but in the GET {id}, they can have multiples

B. 
![image](https://user-images.githubusercontent.com/7662822/213101165-cba5f5ce-814f-4bee-a228-3481b271aa3d.png)

Notice how there is a major difference in how the data is represented for terms served on the GET list vs. the GET {id}. Those are completely different models.

I've encountered other discrepancies as well, but I had these readily available. Again, if there is a desire to shorten the response body for performance, size, or some other constraint, I understand there might be a need for some sort of smaller, summary object being returned so as to point the caller to the individual GET {id} calls to lookup more detailed information, however that doesn't mean the data sets should be completely different.  imo, the terms served and bioguiIds should be identical data objects.

**Comment by pffy** [comment]
Interesting.

YouTube Data APIs have different response bodies, depending on the method call. Each response body shape appears to narrow the scope of the results, maybe?

Are you suggesting, using the YouTube Data API as an example, to always have an array of zero or more `bioguidId` items in the response body?

**Comment by BlankDev117** [comment]
I'm not sure I follow, but that may be a result of miscommunication on my part.

I'm simply trying to point out that the data structures are not consistent for what should be the same data. Yes, for the list endpoint, we could say that the data is scoped to be narrower and less detailed for various reasons than the GET {id} might provide. 

However, being that the data comes from the same basic resource, it seems strange that the data would appear differently for the exact same resource.

For example, on the member GET list api, we are shown to expect a singular id object on the root (referencing docs: https://api.congress.gov/#/member/member_details). 
```
{
        "bioguideId": "L000174",
...
}
```
but on the member {ID}, that object does not exist and instead on a nested identifiers object:
```
{
  ...
  "identifiers": {
         "bioguideId": "L000174"
   }
}
````

For what is the same object, why are these id objects inconsistent? Am I able to reference the same object via different ids ever? Currently, the api doesn't appear to allow me call and request a legislature with more than id, so this seems like an odd structure as there is implication that the bioguideId is the singular unique id to reference this data. What I would've expected on the list here is that the identifiers object would not even be referenced, and instead the main unique id be on the root.

Another example of an inconsistency, being the terms served.

On the GET List, we see data that appears structured as follows:
```
        "served": {
            "Senate": [
                {
                    "end": null,
                    "start": 2020
                }
            ]
        }
```

However, on the GET {ID}, that data, which is supposedly the same data set, is completely different:
````
        "terms": [
            {
                "chamber": "Senate",
                "congress": 116,
                "memberType": "Senator",
                "stateCode": "VT",
                "stateName": "Vermont",
                "termBeginYear": 2019,
                "termEndYear": 2021
            }
````
Firstly, the properties for start and end are completely different. Why is this? Would it not have made sense to simply have a `TermSummary` object on the member list response summary that returns narrower, but identical data?

i.e. it makes more sense to me to have data for the get list to be:

````
"UniqueId": LegislatureId
TermsServed: [
  {
    "Chamber": ...
    "StartYear": ...
    "EndYear": ...
  }
]
````

then on the GET {Id}
````
UniqueId: LegislatureId
TermsServed: [
  {
    "Chamber": ...
    "StartYear": ...
    "EndYear": ...
    "state": ...
    "moreData": ...
  }
],
"MoreData": ...
````

As in, the responses might be different due to being able to provide more details, but they are the same, consistent properties across both, unless explicitly documented that the endpoints are wholly unrelated for some reason.

Why would the terms data sets be so completely different in that StartYear is on the list and TermBeginYear is on the id? It's the same data, but completely decoupled. It makes writing a potential SDK or similar more confusing since the same data is being named and mapped from completely different properties. I'm not the architect and this is just an opinion, but whether narrow or detailed, the data should be consistent for the same properties across the endpoints if it's referring to the same resource or other like datasets; it's adding more complexity where it seems unnecessary.

**Comment by mnewatloc** [comment]
Thank you for bringing this to our attention. We'll work on a fix.
