### ISSUE TITLE
Api Key Usage Query parameter vs. header

### ISSUE THREAD

**Issue by BlankDev117** [LibraryOfCongress/api.congress.gov#75]
This is more of a comment/question on the api key usage being a part of the query vs. a header request.
As a reference:
`Some APIs use API keys for authorization. An API key is a special token that the client needs to provide when making API calls. The key is usually sent as a request header`
https://swagger.io/docs/specification/2-0/authentication/api-keys/

This obviously isn't a hard-fast rule, but it's simply the way I'm used to handling api keys for my own personal projects and other professional works. `https://api.govinfo.gov` also seems to completely ignore this field if it is a header value

**Comment by rbram** [comment]
Hello. The Congress.gov API supports API keys passed through as a URL parameter and in the X-Api-Key header. We’ve updated our [README](https://github.com/LibraryOfCongress/api.congress.gov/blob/main/README.md) to include a link to the [api.data.gov page](https://api.data.gov/docs/api-key/) that explains the methods further.
