### ISSUE TITLE
MultipleObjectsReturned - DJango Error

### ISSUE THREAD

**Issue by lexi-the-cute** [LibraryOfCongress/api.congress.gov#78]
This screenshot shows the same bill showing up twice when paginating.
![Screenshot_20230210_214655](https://user-images.githubusercontent.com/120563837/218235152-dfbfad82-e27c-48fa-8ecd-e154daaed106.png)

This screenshot shows the error message I get when I try to read the bill.
![Screenshot_20230210_214821](https://user-images.githubusercontent.com/120563837/218235180-038a38f2-1e37-4043-bc79-82c10bd50ce3.png)

**Comment by alexisart** [comment]
Here's the URL to access the bill. You'll have to replace the redacted message with your own API key. https://api.congress.gov/v3/bill/21/hr/209?api_key=REDACTED&format=json

**Comment by rbram** [comment]
Hello. Bill data prior to 1973 (93rd Congress) may have data issues, have missing or incorrect metadata, or be incomplete as compared to more current bill data. In some cases, these bills may follow different patterns (e.g., bill numbers were sometimes re-used) when compared to more current bill data. 
We will aim to address data issues in our database like the one reported here, and the updated details will be available on both the congress.gov website and the congress.gov API.
