### ISSUE TITLE
NoReverseMatch - Django

### ISSUE THREAD

**Issue by alexisart** [LibraryOfCongress/api.congress.gov#79]
This screenshot shows Django failing to find the URL resource of 590½.
![Screenshot_20230210_215702](https://user-images.githubusercontent.com/120563837/218235579-c5c26736-7bc1-4726-b99c-17a9406ea884.png)

https://api.congress.gov/v3/bill?api_key=REDACTED&format=json&limit=1&offset=363581
https://api.congress.gov/v3/bill/42/hr/590½?format=json&api_key=REDACTED

**Comment by alexisart** [comment]
The pages that reveal the bills https://api.congress.gov/v3/bill/42/hr/587?format=json and https://api.congress.gov/v3/bill/42/hr/591?format=json work just fine

**Comment by alexisart** [comment]
![Screenshot_20230210_221711](https://user-images.githubusercontent.com/120563837/218236318-a5e65962-505c-4f40-b95b-e92ac704bac4.png)

https://api.congress.gov/v3/bill/42/hr/190?format=json and https://api.congress.gov/v3/bill/42/hr/186?format=json surround the broken bill

**Comment by alexisart** [comment]
![Screenshot_20230210_230126](https://user-images.githubusercontent.com/120563837/218238158-be964591-a369-466a-b189-4631c378f703.png)

https://api.congress.gov/v3/bill/41/hr/1025½?api_key=REDACTED&format=json

**Comment by rbram** [comment]
Thank you for letting us know. Our development team will address this in the future.

**Comment by alexisart** [comment]
This log, *should*, contain a list of every error that the api throws per bill. I did notice that the api didn't go all the way to the first congress, I think it stopped at Congress 6, so I'll have to do some more investigating later

[error.log](https://github.com/LibraryOfCongress/api.congress.gov/files/10728785/error.log)
