### ISSUE TITLE
Unable to download document

### ISSUE THREAD

**Issue by jeremycrumb** [LibraryOfCongress/api.congress.gov#80]
Error message is:
Unable to download document from [https://api.congress.gov/v3/bill/118/hr/917?format=xml&api_key=v6cGFdnRa6JA4LxHWozDoIseLIA5fkQEDSB4VklZ](https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Furldefense.com%2Fv3%2F__https%3A%2Fapi.congress.gov%2Fv3%2Fbill%2F118%2Fhr%2F917%3Fformat%3Dxml%26api_key%3Dv6cGFdnRa6JA4LxHWozDoIseLIA5fkQEDSB4VklZ__%3B!!GFN0sa3rsbfR8OLyAw!ZyB-xc0i0wYjSPuzdESqSLprJ39Ujt6_lI3JiFP6fank_Lj6XE-n8V707lgIOgBwpEftpYWAFUYJQPuiRlRno_iVudlBmZJw%24&data=05%7C01%7Cjeremy.crumb%40thomsonreuters.com%7C8e8a8a9af57f44d70e2b08db103dd63f%7C62ccb8646a1a4b5d8e1c397dec1a8258%7C0%7C0%7C638121630035056328%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=RvNaFdrmb03%2B8wdxwnC4i9PC2xBXVT7m7TLAR2R3B4k%3D&reserved=0) by 'requests', status_code 502, 
'b'<html>\r <head><title>502 Bad Gateway</title></head>\r <body>\r <center><h1>502 Bad Gateway</h1></center>\r </body>\r </html>\r '

**Comment by mnewatloc** [comment]
We can't replicate this. Please try again and let us know if you're still seeing the error.
