### ISSUE TITLE
Given Query URL 404s

### ISSUE THREAD

**Issue by alexisart** [LibraryOfCongress/api.congress.gov#82]
![Screenshot_20230301_220019](https://user-images.githubusercontent.com/120563837/222321014-0e71ace3-6981-41c5-b118-76a4f987eb51.png)
![Screenshot_20230301_220017](https://user-images.githubusercontent.com/120563837/222321016-572950e8-bf77-4660-8dcf-da117025f2ac.png)

No Treaty matches the given query.

**Comment by rbram** [comment]
Thanks for reporting this. We scheduled work to fix this issue.
