### ISSUE TITLE
[error] Small number of bills are numbered using '½', cause breakages.

### ISSUE THREAD

**Issue by c4lliope** [LibraryOfCongress/api.congress.gov#83]
Hello all, I'm glad for a chance to use your API to encourage public access of these records.

I'm poking around some, and I see some odd edge cases in the 30th Congress.
My Ruby code:

```ruby
require 'net/http'
require 'json'

def query_congress address, body = {}
  body[:api_key] = KEY
  JSON.parse Net::HTTP.get URI.parse File.join('https://api.congress.gov/v3', address.to_s) +
    '?' + body.map{|k,s| "#{k}=#{s}" }.join('&')
end

response = query_congress 'bill/30',
  limit: 250,
  sort: 'updateDate+asc'
```

...produces an odd error:

```
=> {"error"=>
  "Reverse for 'bill_details' with keyword arguments '{'congress': 30, 'billType': 'hr', 'billNumber': '260½'}' not found.
2 pattern(s) tried: [
'v3/bill/(?P<congress>(\\\\d+))/(?P<billType>(hr|hres|hconres|hjres|s|sres|sconres|sjres))/(?P<billNumber>(\\\\d+))(?P<file_ext>(\\\\.xml|\\\\.json|/))?$(?i)',
'v2/bill/(?P<congress>(\\\\d+))/(?P<billType>(hr|hres|hconres|hjres|s|sres|sconres|sjres))/(?P<billNumber>(\\\\d+))(?P<file_ext>(\\\\.xml|\\\\.json|/))?$(?i)'
] (NoReverseMatch)",
 "request"=>{"congress"=>"30", "contentType"=>"application/json", "format"=>"json"}}
```

I did a search, and yes indeed - the 30th congress did decide to number a bill as '260½':
https://www.congress.gov/search?q=%7B%22source%22%3A%22all%22%2C%22search%22%3A%22260%5Cu00bd%22%2C%22congress%22%3A30%7D

So clearly, this issue is being caused by a portion of your API's resolver layer which is searching for integer-only numbers:
`(?P<billNumber>(\\\\d+))`

Perhaps you can add a number of fractions inside your resolver's regular expressions to address these edge cases, alongside the usual integer numbering scheme. I'm guessing a functional regular expression could be as simple as:
`(?P<billNumber>([\\\\d½⅓⅔¼¾]+)`

While this issue would hopefully never occur in modern congresses, it is a serious problem in that it completely blocks any `/bill` query responses that need to render this kind of legislation. This makes any congress (e.g. 30th) which decided to use such a numbering scheme inaccessible through your API. As usual, the oldest records pose the most serious challenges.

**Comment by rbram** [comment]
Hello. Thanks for your feedback. We plan to schedule work to handle half bill numbers in the API.

**Comment by c4lliope** [comment]
Also, once you're on this please also check in on congress 14 - they have one called `LXXXV`.
```
Reverse for 'bill_details' with keyword arguments '{'congress': 14, 'billType': 'hr', 'billNumber': 'LXXXV'}' not found. 2 pattern(s) tried: ['v3/bill/(?P<congress>(\\d+))/(?P<billType>(hr|hres|hconres|hjres|s|sres|sconres|sjres))/(?P<billNumber>(\\d+))(?P<file_ext>(\\.xml|\\.json|/))?$(?i)', 'v2/bill/(?P<congress>(\\d+))/(?P<billType>(hr|hres|hconres|hjres|s|sres|sconres|sjres))/(?P<billNumber>(\\d+))(?P<file_ext>(\\.xml|\\.json|/))?$(?i)'] (NoReverseMatch)
```

The halfs appear in: `30`, `38`, `40`, `41`, `42`.
