### ISSUE TITLE
originChamberCode present in bill list but absent from bill itself

### ISSUE THREAD

**Issue by toddfries** [LibraryOfCongress/api.congress.gov#86]
https://api.congress.gov/v3/bill
   .. returns a list of bills, each of which has both originChamber and originChamberCode set
https://api.congress.gov/v3/bill/118/s/1164
  .. returns lots more details about this specific bill and sets originChamber but not originChamberCode

I think originChamberCode should be provided via the API in the second example. yes?

I ran across this while formatting a bill when I had originally used some of the info in the 1st result but thought it was all present in the 2nd.  I'm writing a cli perl program to access this info and if I want to see just a single bill, aka calling the 2nd directly, there is no opportunity to see it in the list of the 1st and get the code.  I've "coded" a fix to fill in this missing info but it would be nicer if the API just provided it.

Thanks!

**Comment by rbram** [comment]
Thanks for bring this to our attention. We’ll pass this feedback on to our developers.
