### ISSUE TITLE
The rate limit is set to 1,000 requests per hour leading to miss the content

### ISSUE THREAD

**Issue by KiranShanmukhappaTR** [LibraryOfCongress/api.congress.gov#88]
For a bill I am looking sponsor, summary and Cosponsor which leads to 3 API  calls in turn  hitting The rate limit is set to 1,000 requests per hour, can get have a API which gives all information(summary,cosposor etc all section) in one API call

**Comment by jordangov** [comment]
(Note that I do not work on api.congress.gov...)

Sadly, the rate limit is set by api.data.gov and applies to any service using that platform. For example, api.regulations.gov has the same limit. I have tried to get that limit increased, but no such luck (and there is no paid option either). The best solution is for applications to create endpoints that better serve the needs of the clients.

**Comment by InfiniteCodeMonkeys** [comment]
I was looking for a friendlier way to download data that doesn't overload the API and I found some links to bulk data from the GPO: 
https://www.govinfo.gov/bulkdata/

https://github.com/usgpo/bulk-data

Hope this helps

**Comment by jordangov** [comment]
@apreiter18 Any information as to how this was "completed"? I don't see a linked PR or comment on the resolution.

**Comment by apreiter18** [comment]
In March 2024, the rate limit for the Congress.gov API was increased from 1000 calls/hour to 5000 calls/hour, @jordangov
