### ISSUE TITLE
Congress Member Images

### ISSUE THREAD

**Issue by Sparkletins** [LibraryOfCongress/api.congress.gov#92]
I am trying to access the images of congress members. This works fine by getting the link to their image through the API. The problem comes in when I follow that link to the specific image through and HTTP get request where I get a 403 forbidden response. The response states that I must enable Javascript and cookies. It works fine on local environment but does not work through other environments such as postman.

**Comment by rbram** [comment]
Hello. Thanks for your feedback. We are looking into this.

**Comment by dlewis2017** [comment]
I wonder if this is linked to the issue I create [here](https://github.com/LibraryOfCongress/api.congress.gov/issues/192). Possibly not because this seems to be web based but linking just in case. @Sparkletins did you ever figure out the issue?
