### ISSUE TITLE
Question about unexpected committee results

### ISSUE THREAD

**Issue by mattpaz** [LibraryOfCongress/api.congress.gov#95]
I'm wondering if the `committee` endpoint is returning some stale data elements?

For example, the **Senate Commerce, Science, and Transportation Subcommittee on Communications, Technology, Innovation, and the Internet** `sscm26` is listed in the results below: 

https://api.congress.gov/v3/committee/118?limit=250&api_key=TBD

And here (without members):
https://api.congress.gov/v3/committee/senate/sscm26?format=json&limit=250&api_key=TBD

But it doesn't seem to be listed in any of these resources:

* https://www.senate.gov/general/committee_membership/committee_memberships_SSCM.xml
* https://www.commerce.senate.gov/commerce-subcommittees
* https://www.senate.gov/committees/index.htm

Can you advise as to whether this is an anomaly (of if there are alternative ways the data should be interpreted)?

Thanks!

---

Discovered via work here:
https://github.com/unitedstates/congress-legislators/issues/886

**Comment by mnewatloc** [comment]
Thank you for letting us know about this issue. We've created a bug ticket to fix this.
