### ISSUE TITLE
403: Authorization Failed

### ISSUE THREAD

**Issue by dlewis2017** [LibraryOfCongress/api.congress.gov#96]
403:

body: {
  "error": "Authorization failed"
}
headers: {
 cf-cache-status: DYNAMIC 
 cf-ray: 7d03f025ab2241ef-EWR 
 content-length: 39 
 content-type: application/json 
 date: Thu, 01 Jun 2023 02:13:33 GMT 
 server: cloudflare 
 vary: Accept 
}
Getting this error. Tried to get a new API key and am continuing to get this issue.

Thanks,

**Comment by mnewatloc** [comment]
We're sorry you're running into this error. Can you try again and let us know if it's still not working?

**Comment by dlewis2017** [comment]
It still does not work

**Comment by mnewatloc** [comment]
Can you share your query with us (with your API key omitted)?

**Comment by dlewis2017** [comment]
I'm using the swagger and just calling the bill endpoint (https://gpo.congress.gov/#/bill/bill_list_all)
I've also tried it calling this url: https://api.congress.gov/v3/bill?api_key=[INSERT_KEY] in javascript using node-fetch

**Comment by mnewatloc** [comment]
Please use api.congress.gov instead of gpo.congress.gov. gpo.congress.gov is a legacy url and shouldn't be used.

**Comment by dlewis2017** [comment]
@mnewatloc The swagger at api.congress.gov works. However, I mentioned in my previous comment that I tried a rest call with api.congress.gov as well that didn't work. It does work now either way but I don't think I changed any code. Thanks either way! I'd be curious to know what the original issue was though for the next time I run into it
