### ISSUE TITLE
updateTime and updateTimeIncludingText are in the future

### ISSUE THREAD

**Issue by bonbonbaron** [LibraryOfCongress/api.congress.gov#99]
When I query with fromDatetime set to the current time, I get lots of bills whose elements mentioned in the title are dated in the future. Is this an error?

**Comment by mnewatloc** [comment]
Is it a time zone issue? API responses are in Zulu time following ISO 8601 Datetime formats. If you are willing, maybe you could share your search queries (API key omitted) so we can take a look at what you are seeing.
